### PR TITLE
fix(table): single nested parents should have bold font weight

### LINKED ISSUE #1647: [Table] Single-nested tables' parent categories should be bold text
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Single-nested tables' parent categories should have bold text to further distinguish between parent and child items

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-single-nested-hierarchy
2. See that the parents values are not in bold text

### Expected behavior

Values should be bold for parents

### Environment/versions:

- OS: MacOS
- Browser:chrome
- `carbon-addons-iot-react` version: v2.114.0

### Additional context

Related internal design: https://ibm.invisionapp.com/share/KWO0FZ5BHQ9#/screens/319695909

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Will add myself

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1647 

**Summary**

- To meet the proper design of single-nested hierarchy Table's, this PR adds `font-weight: bold` to parent category/rows

**Change List (commits, features, bugs, etc)**

- Add the font-weight based off whether `hasRowNesting: { hasSingleNestedHierarchy: true}` and whether there is children or not (AKA is the row a parent)

**Acceptance Test (how to verify the PR)**

- Go to ?path=/story/watson-iot-table--stateful-example-with-single-nested-hierarchy and see that all parents are bold, while all children are regular font-weight

### CODE REVIEW

**Review by JoelArmendariz — APPROVED** [review]

File: src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx [hunk 1]
```diff
@@ -177,6 +177,17 @@ const StyledTableExpandRow = styled(({ hasRowSelection, ...props }) => (
   <TableExpandRow {...props} />
 ))`
   &&& {
+    ${
+      // if single nested hierarchy AND there are children rows (meaning this is a parent),
```
Comment (bjornalm) [inline src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx:181]: I think that this comment is superfluous. If you would extract `props['data-child-count'] > 0` into a `isParent` const then the code would read exactly like your comment.

**Review by bjornalm — APPROVED** [review]
Nice work

File: src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx (hunk 1 above)
Comment (sstone2423) [reply src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx:181]: Great point. Looks like it was merged, but I should have another fix coming in soon where I can add this in
