### PR TITLE
fix(emptystate): adjust proptypes schema

### LINKED ISSUE #3370: [Table] incorrect PropTypes for emptyState
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The Table has incorrect PropTypes for the prop `view.table.emptyState`. It uses `EmptyStatePropTypes` which defines a configuration object where all property values are of type `PropTypes.node`, but the actual underlying `EmptyState` component used expects strings for several of the props. This is true for `message`, `messageWithFilters`, `buttonLabel` and `buttonLabelWithFilters`. Only the actual `messageBody` can be a node.

### To Reproduce

na

### Expected behavior

PropTypes in `EmptyStatePropTypes` should match the types they are matched against in the underlying `EmptyState` component.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by erzhan-temir-mamyrov**
Closes #3370 

**Summary**

- Change PropTypes schema for `EmptyState`

**Change List (commits, features, bugs, etc)**

- PropTypes schema
- Public API snapshot update

**Acceptance Test (how to verify the PR)**

- Go to [this commit](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3567/commits/0aeda1e8d8aba1b231e2904dc82f60a6d6ce261c)
- Verify that PropTypes fields were converted from single `node` to `oneOfType([PropTypes.node, PropTypes.string])`

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/Table/TablePropTypes.js [hunk 1]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
 
 export const EmptyStatePropTypes = PropTypes.oneOfType([
   PropTypes.shape({
-    message: PropTypes.node.isRequired,
-    messageBody: PropTypes.node,
+    message: PropTypes.oneOfType([PropTypes.node, PropTypes.string]).isRequired,
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:52]: This should be only string.
message: PropTypes.string.isRequired,

File: packages/react/src/components/Table/TablePropTypes.js [hunk 2]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
...
+    messageBody: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
     /* Show a different message if no content is in the table matching the filters */
-    messageWithFilters: PropTypes.node,
-    messageWithFiltersBody: PropTypes.node,
+    messageWithFilters: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:55]: only string here

File: packages/react/src/components/Table/TablePropTypes.js [hunk 3]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
...
+    messageWithFiltersBody: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:56]: only string here

File: packages/react/src/components/Table/TablePropTypes.js [hunk 4]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
...
     /* If a label is not provided, no action button will be rendered */
-    buttonLabel: PropTypes.node,
+    buttonLabel: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:58]: only string here

File: packages/react/src/components/Table/TablePropTypes.js [hunk 5]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
...
     /* Show a different button label if no content is in the table matching the filters */
-    buttonLabelWithFilters: PropTypes.node,
+    buttonLabelWithFilters: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:60]: only string here

File: packages/react/src/components/Table/TablePropTypes.js [hunk 6]
```diff
@@ -49,15 +49,15 @@ export const RowActionsStatePropTypes = PropTypes.arrayOf(
...
-    messageBody: PropTypes.node,
+    message: PropTypes.oneOfType([PropTypes.node, PropTypes.string]).isRequired,
+    messageBody: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
     /* Show a different message if no content is in the table matching the filters */
-    messageWithFilters: PropTypes.node,
-    messageWithFiltersBody: PropTypes.node,
+    messageWithFilters: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
+    messageWithFiltersBody: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
     /* If a label is not provided, no action button will be rendered */
-    buttonLabel: PropTypes.node,
```
Comment (jessieyan) [inline packages/react/src/components/Table/TablePropTypes.js:58]: only string here

**Review by jessieyan — CHANGES_REQUESTED** [review]
Looked at `<EmptyTable>` and `<EmptyState> `component,  

There are string type:
messageWithFilters,
message,
buttonLabel,
 buttonLabelWithFilters,

These are either strings or node:
 messageBody,
 messageWithFiltersBody,

File: packages/react/src/components/Table/TablePropTypes.js (hunk 1 above)
Comment (davidicus) [reply packages/react/src/components/Table/TablePropTypes.js:52]: Since this is a minor version bump we must keep  the node proptype for backwards compatibility.

**Comment by davidicus** [comment]
Looking at the actual issue, I guess we need to see if we were getting proptype errors previously by using a node. If we were getting prop type errors no matter what then we might want to look at if EmptyState component to see if we refactor it to use a node. My original concern on first glance is that we were requiring the node prop type and are now changing it on our users.  @erzhan-temir-mamyrov If you want to discuss tomorrow  let me know and we can hop on a quick call to discuss. Thanks @jessieyan for pointing out the issues concerns.

File: packages/react/src/components/Table/TablePropTypes.js (hunk 1 above)
Comment (erzhan-temir-mamyrov) [reply packages/react/src/components/Table/TablePropTypes.js:52]: @jessieyan Thank you for commenting on this. I changed `PropTypes.node` to `PropTypes.oneOfType([PropTypes.node, PropTypes.string])` for backward compatibility. In the last commits I modified `EmptyState` component itself, for prop types of `string` and `node`.

**Review by davidicus — APPROVED** [review]
