### PR TITLE
fix(suiteheader): allow keyboard navigation

### LINKED ISSUE #2303: MAS Header-None of the options are open in help, profile and app switcher using the keyboard
As part of accessibility testing when trying to open the help (system information, what’s new..), profile (Profile option 1, logout) and App Switcher options in Mas Header using the keyboard, none of them are open.
image

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2303 

**Summary**

Previously none of the actionItem menus or panels would work when navigating with the keyboard. This PR fixes that. It checks for the existence of onClick or onKeyDown handlers and uses those if given. If an onClick handler is given, but not an onKeyDown, it creates a default to make sure the event is still triggered onKeyDown. It accounts for the differences in A and BUTTON tags and maintains backwards compatibility for event handlers currently being passed.

**Change List (commits, features, bugs, etc)**

- add onKeyDown handlers to items that don't have them to mimic the onClick behavior
- add tests to cover keyboard navigation
- update snapshots

**Acceptance Test (how to verify the PR)**

- keyboard navigation on SuiteHeader stories should allow you to choose items from the help, user, or appswitcher menus

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Everything else still works as expected

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
This looks good code wise but the checks are failing for some reason.

**Comment by kevinsperrine** [comment]
> This looks good code wise but the checks are failing for some reason.

Just the netlify deploy preview didn't finish in time, so it failed, right? Everything else is green to me.

**Comment by davidicus** [comment]
> > This looks good code wise but the checks are failing for some reason.
> 
> Just the netlify deploy preview didn't finish in time, so it failed, right? Everything else is green to me.

yes, but consistently. I have restarted a few times. This doesnt mean that it is not netlify issue. I am just going to try to rebuild to be sure

**Comment by davidicus** [comment]
OK. Netlify finally built and returned its status.

File: packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx [hunk 1]
```diff
@@ -96,12 +97,31 @@ const HeaderActionPanel = ({
       >
         <ul aria-label={item.label}>
           {item.childContent.map((childItem, k) => {
-            const ChildElement = childItem?.metaData?.element || 'a';
+            const { element, ...metaData } = childItem?.metaData ?? {};
+            const ChildElement = element || 'a';
+            const onKeyDownClick = (e) => e.target.click();
+
+            // otherwise if the item is an A and doesn't have an onClick event
```
Comment (bjornalm) [inline packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx:104]: nit: comment starting with otherwise, was the code refactored and you forgot the comment?

File: packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx [hunk 2]
```diff
@@ -96,12 +97,31 @@ const HeaderActionPanel = ({
...
+            const onClick =
+              ChildElement === 'a' && !metaData?.onClick
+                ? undefined
+                : // otherwise, if an onClick exists use that, or fallback to a noop.
+                  metaData?.onClick || (() => {});
+
+            // if item has onKeyDown use that otherwise, fallback to onClick if it exists
+            // or create a custom handler to trigger the click
+            const onKeyDown = metaData?.onKeyDown
+              ? childItem.metaData.onKeyDown
```
Comment (bjornalm) [inline packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx:115]: why `childItem.metaData.onKeyDown` ?

**Review by bjornalm — APPROVED** [review]
Nice work, just 2 questions

File: packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx:104]: yeah, refactored and missed.

File: packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx (hunk 2 above)
Comment (kevinsperrine) [reply packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx:115]: same. refactored and missed.
