### PR TITLE
fix(table): with multiple tables, select all button doesn't work

### LINKED ISSUE #1084: [StatefulTable] cannot select all in StatefulTable if that table is in a modal
### Describe the bug

I add a StatefulTable in a modal, table data is populated, each line can be selected, but "Select all" checkbox cannot be selected, when click "Select all" checkbox, no change in the table, only the modal "X" close icon is focused.

### To Reproduce

1. Add StatefulTable in a modal, show in page
2. Click on 'select all' checkbox in the modal
3. See error, no line is selected, "X" close icon in the modal is focused

image

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/codesandbox-yxbkg

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. firefox, chrome]
- `carbon-addons-iot-react` version: [e.g. `v2.63.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by Jessepy**
Closes #1084

**Summary**

- When there is a table in a modal with another table outside the modal, you can't select all. Fixed by adding unique id to select all button.

**Change List (commits, features, bugs, etc)**

- As tables are created, the select all button has an incrementing id
- Updated snapshots that had select all buttons
- Added test to ensure show it works

**Acceptance Test (how to verify the PR)**

- make sure that test runs without error
- if you want to go the extra mile, verify visually by adding 2 tables, one in a modal, in a story then ensure select all buttons work

### CODE REVIEW

File: src/components/Table/TableHead/TableHead.jsx [hunk 1]
```diff
@@ -279,7 +282,7 @@ const TableHead = ({
                     https://github.com/IBM/carbon-components-react/issues/1088 */}
             <Checkbox
               disabled={isDisabled}
-              id="select-all"
+              id={`select-all${selectAllId}`}
```
Comment (tay1orjones) [inline src/components/Table/TableHead/TableHead.jsx:285]: What if we instead modified this component to take the tableId prop and pass it down from `<Table>`?

It would then be unique to the table but also would be configurable

Comment (Jessepy) [reply src/components/Table/TableHead/TableHead.jsx:285]: Sounds like a good solution, I'll get that done!

File: src/components/Table/Table.jsx [hunk 2]
```diff
@@ -178,7 +180,7 @@ const propTypes = {
 };
 
 export const defaultProps = baseProps => ({
-  id: 'Table',
+  id: `Table_${tableIdNumber}`,
```
Comment (tay1orjones) [inline src/components/Table/Table.jsx:183]: This incrementing counter feels odd. I don't think it's necessary as consumers (and our stories) should configure a tableID, although it's not considered a required prop. 

Should we just use `Date.now()`?

Comment (sstone2423) [reply src/components/Table/Table.jsx:183]: > I think something is up with the merge from resolving the conflicts - there are now lots of unrelated changes in here @davidicus @sstone2423
> 
> RowActionsCell, Table 'onColumnResize callback' story, ComposedModal, TableHead, columnWidthUtilityFunctions, etc

It looks like that charting changes are correct here. The diff is the same as master for the obvious ones that I know in BarChartCard. Could we close and reopen this, or reset the base and hopefully the diff will re-correct

**Comment by sstone2423** [comment]
> I think something is up with the merge from resolving the conflicts - there are now lots of unrelated changes in here @davidicus @sstone2423
> 
> RowActionsCell, Table 'onColumnResize callback' story, ComposedModal, TableHead, columnWidthUtilityFunctions, etc

@tay1orjones 
It looks like that charting changes are correct here. The diff is the same as master for the obvious ones that I know in BarChartCard. Could we close and reopen this, or reset the base and hopefully the diff will re-correct?

**Comment by sstone2423** [comment]
@tay1orjones the diff is normal after resetting the base 👍

File: src/components/Table/Table.jsx (hunk 2 above)
Comment (bjornalm) [reply src/components/Table/Table.jsx:183]: Looks like a lot of people are adding counters to combat these kind of problems, but I  like @tay1orjones suggests another option is to generate a unique ID. With this solution the table is getting a new ID on each re-render, which doesn't seem optimal.

Perhaps we isolate the fix to the TableHead.jsx file and reduce some table complexity while keeping the ID fixed while the component is alive? We could use lodash and the react state do something like `const [ checkboxID ] = useState(() => uniqueId('select-all-'))` in TableHead.jsx.

I did notice that the checkbox itself has the following comment

```
/* TODO: Replace checkbox with TableSelectAll component when onChange bug is fixed
                    https://github.com/IBM/carbon-components-react/issues/1088 */
```

The URL is dead now, but we should probably look into that before adding more workarounds with the current checkbox.

Comment (tay1orjones) [reply src/components/Table/Table.jsx:183]: Even further, could probably avoid state and just useMemo?
```js
const tableID = useMemo(() => `table-${Date.now()}-${tableId}`, [tableId]); // could use counter instead of Date.now
```

IIRC That comment is pretty old, from the initial implementation of the Table. I've opened https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1520 to address separately

File: src/components/Table/TableHead/TableHead.jsx [hunk 3]
```diff
@@ -40,6 +40,7 @@ const { iotPrefix } = settings;
 const { TableHead: CarbonTableHead, TableRow, TableExpandHeader } = DataTable;
 
 const propTypes = {
+  id: PropTypes.string.isRequired,
```
Comment (tay1orjones) [inline src/components/Table/TableHead/TableHead.jsx:43]: I think we usually follow the convention that internal table components take a `tableId` instead of `id`
```suggestion
  tableId: PropTypes.string.isRequired,
```

File: src/components/Table/Table.jsx (hunk 2 above)
Comment (bjornalm) [reply src/components/Table/Table.jsx:183]: Yea, useMemo could work but it is not guaranteed that the ID will not change, according to the docs:
"In You may rely on useMemo as a performance optimization, not as a semantic guarantee"

File: src/components/Table/Table.jsx [hunk 4]
```diff
@@ -395,7 +397,7 @@ const Table = props => {
       view.toolbar.customToolbarContent ||
       tooltip ? (
         <TableToolbar
-          tableId={id}
+          tableId={id || tableId}
```
Comment (stuckless) [inline src/components/Table/Table.jsx:400]: trying to understand what this is doing... basically if we are passed an ID then we use it, otherwise we use the tableId which comes from the state that is some randomly generated id?  Why is tableId something that is stateful?

Comment (tay1orjones) [reply src/components/Table/Table.jsx:400]: I think github auto collapsed the outdated conversation we had about it in from my review: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1470#discussion_r471747991

File: src/components/Table/Table.jsx (hunk 2 above)
Comment (stuckless) [reply src/components/Table/Table.jsx]: Seems to me that IF the ID is required for the table to operate correctly, then it should be required.  Hacking the id to avoid using a require prop seems wrong.

**Comment by tay1orjones** [comment]
This may also fix https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1086

File: src/components/Table/Table.jsx (hunk 4 above)
Comment (davidicus) [reply src/components/Table/Table.jsx:400]: @stuckless we are  using the useState hook to get a value that is not updated on re-renders. Since the default is only evaluated once and we do not provide an update method it will be unique for each table instance.
