### PR TITLE
fix(DateTimePickerV2): :focus not working in firefox

### LINKED ISSUE #3619: [DateTimePickerV2] The focus for date time input field is working in chrome when doing tabination. But in FF it's not showing the Focus.
The focus for date time input field is working in chrome and Safari when doing tabination. But in FF it's not showing the Focus.
https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select
In Chrome, showing the focus when doing tabination (PAL Storybook)
image
(GRAPHITE)
In FireFox, not showing the focus when doing tabination 
image
In Chrome, showing the focus
image

### PR DESCRIPTION
**Pull request by jessieyan**
Closes #3619 

**Summary**

- If a child element sets `outline`, css` :focus `does not work on either child or parent element anymore in firefox.  

- The previous invalid style was applied to `${iotPrefix}--date-time-picker__box`, it sets `outline` to `$danger-01`. If I set :focus or :focus-visible on the same element. The outline stays `$danger-01`. And the parent `:focus outline` not working either. 
- I have to move the invalid style to the parent wrapper to make it work in firefox.

**Change List (commits, features, bugs, etc)**

- move class to the wrapper element
- update the single select story to make sure tab key works

**Acceptance Test (how to verify the PR)**
Tab key
- go to single select story
- check the invalid check box in knobs
- click on the text "DateTimePickerV2 Single Select"
- push tab key
- make sure the input is in focus with blue outline

Mouse click
- go to single select story
- check the invalid check box in knobs
- click on the datetime input
- make sure the input is in focus with blue outline

Mouse click
- go to Selected absolute story
- check the invalid check box in knobs
- click on the datetime input
- make sure the input is in focus with blue outline

https://user-images.githubusercontent.com/24279794/204611689-b735dcbd-5927-41d0-b42b-2c239014118f.mov

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by jessieyan** [comment]
Looks like the preview build is not deployed

File: packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx [hunk 1]
```diff
@@ -873,7 +874,6 @@ const DateTimePicker = ({
           className={classnames({
             [`${iotPrefix}--date-time-picker__box--full`]: !hasIconOnly,
             [`${iotPrefix}--date-time-picker__box--light`]: light,
-            [`${iotPrefix}--date-time-picker__box--invalid`]: invalidState,
```
Comment (davidicus) [inline packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx:876]: We may want to leave this one, as someone may be using it as a selector.

**Comment by jessieyan** [comment]
Tested in Firefox again. It worked as expected.

**Review by davidicus — APPROVED** [review]
