### PR TITLE
chore(Card Editor) Fix downsample methods

### LINKED ISSUE #3427: Downsample Method for dashboard editor
Downsample Method for dashboard editor 

### What package is this for?

- [x] React
- [ ] Angular

### Summary
Create new dropdown for V2 data items in dashboard editor 

More details can be found in https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/3955

### PR DESCRIPTION
**Pull request by EdmondCShaffer**
Closes #3427 

**Summary**
changed downsample implementation 

**Change List (commits, features, bugs, etc)**

- Added Version prop and removed hasDownsampleMethods from DataSeriesFormItemModal 

**Acceptance Test (how to verify the PR)**

- tests here

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx [hunk 1]
```diff
@@ -71,6 +71,7 @@ const propTypes = {
     dataSourceId: PropTypes.string,
     dataFilter: PropTypes.objectOf(PropTypes.string),
     type: PropTypes.string,
+    isStreamingMetricEnabled: PropTypes.bool,
```
Comment (davidicus) [inline packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx:74]: A convention for our library is for booleans to start with `has`
```suggestion
   hassStreamingMetricEnabled: PropTypes.bool,
```

**Review by davidicus — CHANGES_REQUESTED** [review]
This looks good. Just small change to name of  boolean prop

**Review by davidicus — APPROVED** [review]
Good to go once checks pass
