### PR TITLE
fix(datetimepicker): handle null select

### LINKED ISSUE #2653: [DateTimePicker] cannot deselect the default selection with 'null' value
### What package is this for?

- [ ] React
- [x] Angular

### Describe the bug

not able to deselect the default selected value with `[selected] = "null"`.

Screen Shot 2021-08-11 at 1 56 23 PM

Screen Shot 2021-08-11 at 1 13 14 PM

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

Should not select any date options when pass `null` to property `selected`.

Screen Shot 2021-08-11 at 1 13 14 PM

### Environment/versions:

- OS: MacOS
- Browser: chrome, firefox
- `carbon-addons-iot-react` version: 2.146.0-next.70

### Additional context

I think this issue is caused by
Screen Shot 2021-08-11 at 1 53 41 PM

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by sophiiae**
Closes #2653 

**Summary**

- summary_here

**Change List (commits, features, bugs, etc)**

- items_here

**Acceptance Test (how to verify the PR)**

- tests here

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/angular/src/date-time-picker/date-time-picker.component.ts [hunk 1]
```diff
@@ -233,13 +234,15 @@ export class DateTimePickerComponent implements OnChanges, OnInit {
...
-      this.selected = [this.dateTimeRanges[0].key];
+      this.selected = [null];
     }
   }
 
   formatCurrentRangeTitle() {
     const [rangeOrType] = this.selected;
-    if (rangeOrType === 'RELATIVE' || rangeOrType === 'ABSOLUTE') {
+    if (!rangeOrType) {
+      return '';
```
Comment (cal-smith) [inline packages/angular/src/date-time-picker/date-time-picker.component.ts:244]: We should probably add a `placeholder` input to return in this case (I'm assuming if you're passing `[null]` you don't want a specific selection)

File: packages/angular/src/date-time-picker/date-time-picker.component.ts [hunk 2]
```diff
@@ -48,6 +48,7 @@ export type DateRange = [Date, Date];
         (keydown.space)="togglePicker()"
         [ibmTooltip]="formatCurrentRange()"
         [offset]="tooltipOffset"
+        [disabled]="!formatCurrentRangeTitle()"
```
Comment (cal-smith) [inline packages/angular/src/date-time-picker/date-time-picker.component.ts:51]: Good thinking, though if we need to disable this we should probably have a separate `disabled` input we can pass down

**Review by cal-smith — CHANGES_REQUESTED** [review]
A couple suggestions, but otherwise thanks for taking this on!

**Review by cal-smith — APPROVED** [review]
LGTM! Thanks!
