### PR TITLE
fix(card-editor): allow initial data items

### LINKED ISSUE #1742: Need to support initial data series items in card editor
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The `CardEditor` wasn't handling initial existing data series items in the data series section

### Expected behavior

The consumer should be able to use existing dataItems from their dashboard in the `CardEditor`

### Additional context

Just need to reformat the incoming data

### PR DESCRIPTION
**Pull request by JoelArmendariz**
Closes #1742

**Summary**

Handles initial dataItems, and adds a couple optional props.

**Change List (commits, features, bugs, etc)**

Add:
`getValidTimeRanges`
`onCardChange`

Updates proptypes for `dataItems`

**Acceptance Test (how to verify the PR)**

Go to the `initialValue` and `with custon onCardChange` story in `DashboardEditor` and make sure that the dataseries section in `TimeSeriesCards` works properly

### CODE REVIEW

File: src/components/DashboardEditor/DashboardEditor.jsx [hunk 1]
```diff
@@ -307,11 +323,16 @@ const DashboardEditor = ({
               setDashboardJson({
                 ...dashboardJson,
                 cards: dashboardJson.cards.map((card) =>
-                  card.id === cardConfig.id ? cardConfig : card
+                  card.id === cardConfig.id
```
Comment (bjornalm) [inline src/components/DashboardEditor/DashboardEditor.jsx:326]: Perhaps the `onChange` could be a function with an explanatory name now since the inline function has grown larger

**Review by bjornalm — COMMENTED** [review]
Looks good, only have a few suggested changes related to DRYness and readability.

File: src/components/CardEditor/CardEditForm/CardEditForm.jsx [hunk 2]
```diff
@@ -47,10 +47,20 @@ const propTypes = {
...
+   * getValidTimeRanges(card, selectedDataItems)
+   */
+  getValidTimeRanges: PropTypes.func,
+  /** an array of dataItems to be included on each card
    * this prop will be ignored if getValidDataItems is defined
    */
-  dataItems: PropTypes.arrayOf(PropTypes.string),
+  dataItems: PropTypes.arrayOf(
+    PropTypes.shape({
+      dataSourceId: PropTypes.string,
```
Comment (davidicus) [inline src/components/CardEditor/CardEditForm/CardEditForm.jsx:60]: It looks like we are using these values in the component logic but we do not have this as required or do any checks for its value. Is this correct? if so we should do one or the other.

**Comment by bjornalm** [comment]
I don't find the story `with custon onCardChange`.

When testing story `with initial value` I found this:
a)
1. Go to https://deploy-preview-1743--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--with-initial-value
2. Click Time series line in the gallary
3. Now click the existing TimeSeries card in the dashboard grid
4. Notice how the Data item in the inspector panel is not showing anything, unlike if yo would have clicked the TimeSeries card in the dashboard grid directly

b)
1. Go to https://deploy-preview-1743--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--with-initial-value
2. Click the existing TimeSeries card in the dashboard grid
3. Uncheck the selection in Data item dropdown
4. Notice how the Data item dropdown is empty
image

File: src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx [hunk 3]
```diff
@@ -214,11 +225,12 @@ const DataSeriesFormItem = ({
           label={mergedI18n.selectDataItems}
           direction="bottom"
           itemToString={(item) => item.text}
+          initialSelectedItems={initialSelectedItems}
           items={
             validDataItems
-              ? validDataItems.map((dataItem) => ({
-                  id: dataItem,
-                  text: dataItem,
+              ? validDataItems.map(({ dataSourceId, label }) => ({
```
[the remark this answers is not in the document]
Comment (JoelArmendariz) [reply src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx]: I have changed this to a reuse-able function.

File: src/components/DashboardEditor/DashboardEditor.jsx (hunk 1 above)
Comment (JoelArmendariz) [reply src/components/DashboardEditor/DashboardEditor.jsx]: Good call, I extracted it to `handleOnCardChange`

File: src/components/CardEditor/CardEditForm/CardEditForm.jsx (hunk 2 above)
Comment (JoelArmendariz) [reply src/components/CardEditor/CardEditForm/CardEditForm.jsx]: Actually any logic involving the `dataItems` acts properly because it defaults to an empty array when not present. I was unable to find anywhere that it would cause problems.

**Comment by JoelArmendariz** [comment]
> I don't find the story `with custon onCardChange`.
> 
> When testing story `with initial value` I found this:
> a)
> 
>     1. Go to https://deploy-preview-1743--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--with-initial-value
> 
>     2. Click Time series line in the gallary
> 
>     3. Now click the existing TimeSeries card in the dashboard grid
> 
>     4. Notice how the Data item in the inspector panel is not showing anything, unlike if yo would have clicked the TimeSeries card in the dashboard grid directly
> 
> 
> b)
> 
>     1. Go to https://deploy-preview-1743--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-dashboardeditor--with-initial-value
> 
>     2. Click the existing TimeSeries card in the dashboard grid
> 
>     3. Uncheck the selection in Data item dropdown
> 
>     4. Notice how the Data item dropdown is empty
>        image

Ah weird.. The merge got rid of that story, sorry about that. I added it back.
I also fixed the empty dropdown problem. @bjornalm

File: src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx [hunk 4]
```diff
@@ -61,10 +61,15 @@ const propTypes = {
    * getValidDataItems(card, selectedTimeRange)
    */
   getValidDataItems: PropTypes.func,
-  /** an array of dataItem string names to be included on each card
+  /** an array of dataItems to be included on each card
    * this prop will be ignored if getValidDataItems is defined
    */
-  dataItems: PropTypes.arrayOf(PropTypes.string),
+  dataItems: PropTypes.arrayOf(
```
[the remark this answers is not in the document]
Comment (JoelArmendariz) [reply src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx]: I have extracted this proptype to be re-used after one definition.

File: src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx [hunk 5]
```diff
@@ -125,6 +125,12 @@ export const formatSeries = (selectedItems, cardJson) => {
   return series;
 };
 
+export const formatDataItemsForDropdown = (dataItems) =>
```
Comment (bjornalm) [inline src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx:124]: Does it have to be exported?

**Review by bjornalm — APPROVED** [review]

**Comment by bjornalm** [comment]
Nice work!

**Review by tay1orjones — APPROVED** [review]

File: src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx (hunk 5 above)
Comment (JoelArmendariz) [reply src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx:124]: Oh my intentions were to add a test case, but I forgot. Will add into the next iteration
