### PR TITLE
fix(table): don't display native title when using tooltip in header

### LINKED ISSUE #2937: [Data table] Definition tooltip in column header
### What package is this for?

- [x] React
- [ ] Angular

### Summary

To help standardize this across AI Apps, we'll be moving towards using [definition tooltips](https://www.carbondesignsystem.com/components/tooltip/usage/#definition-tooltip) instead of info icons in data table column headers, to help reduce the column header clutter, and so that there isn't a competing _info icon_ with the _sort icon_. The column header **type style** will stay the same as what's used in data tables.

This was feedback that we received from the MAS team a while back (@lukefirth) and we've noticed get adopted more and more across other designs.

Teams should be able to put whatever content they need in the tooltip.

[PAL guidance](https://pages.github.ibm.com/ai-applications/design/components/datatable/general#definition-tooltips)

Screen Shot 2021-10-07 at 3 49 47 PM

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2937 

**Summary**

- We had previously added definition tooltips to column headers, but there was a minor issue of the native browser title appearing on hover. This fixes that and adds some test cases.

**Change List (commits, features, bugs, etc)**

- set `title` prop to undefined when using tooltips in column headers
- add test cases
- remove old enzyme test
- add long text block example to Stateful example story

**Acceptance Test (how to verify the PR)**

- ensure native browser tooltip doesn't appear when hovering over a tooltip title in column headers

**Regression Test (how to make sure this PR doesn't break old functionality)**

- ensure titles still work without tooltips
- tooltips still function as expected

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx [hunk 1]
```diff
@@ -131,7 +131,9 @@ const TableCellRenderer = ({
     <span
       className={myClasses}
       title={
-        typeof children === 'number' && locale
+        useTooltip || tooltip
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx:134]: Good that you caught both scenarios

**Review by bjornalm — COMMENTED** [review]
Code looks good, build has failed though and I just wanna try it before approval.

**Review by davidicus — APPROVED** [review]

**Comment by davidicus** [comment]
@bjornalm preview ready

**Review by bjornalm — APPROVED** [review]
