### PR TITLE
fix(table): prevent column widths below min width

### LINKED ISSUE #2474: [Table] min-width of column not always respected
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
The min-width is not being respected on initial rendering for columns with undefined width property.

### To Reproduce

1. Go to https://deploy-preview-2473--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--with-options-to-explore-column-settings and set "table container width" to be 300px.
2. Note that the columns are below the min-width (62px) that is used for column resize.

### Expected behavior

If the columns do not have an explicit width defined they should not be allowed to shrink below the min-width.

### Environment/versions:

- OS: all
- Browser: all
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

Relates to needed specification for table columns #2471

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #2474

**Summary**
Fix to prevent the table from rendering column widths below the min width on the initial rendering

**Change List (commits, features, bugs, etc)**
- Removed old (CSS) style prop containing widths that was not being used
- Added new check on initial rendering that changes widths below the minimum to the default width
- Added unit test

Instead of affected widths being changed to the actual min-width (62px) I used the default width of 150px instead after discussion with @JordanWSmith15. We reasoned that the users would rarely want the 62px width since it doesn't show much of the column header. The 62px min width still stays as the lower boundary for when the user resizes the columns.

**Acceptance Test (how to verify the PR)**
Go to https://deploy-preview-2669--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--with-options-to-explore-column-settings use the default knob coniguration

**- Test initial column widths**
1. Use config: Initial column width: undefined, table container width: 300px, hasResize:true, wrapCellText: always, useAutoTableLayoutForResize:false, preserveColumnWidths:false
2. Make sure the columns get the default width of 150px. Before the fix the widths would have been below min width.
3. Change "table container width" to 800px. Verify that the columns get a width of 100px. This is the unmodified width set by the browser which we don't modify since it is above the min width.
4. Change "table container width" to "auto" (for a wide browser window) and make sure the columns widths are distributed evenly  

**- Test columns widths on window resize since it uses the same code**
1. Use config: Initial column width: undefined, table container width: auto, hasResize:true, useAutoTableLayoutForResize:true, preserveColumnWidths:false
2. Resize browser window and make sure column widths still adjust to the text of the columns headers and that the min-width of 62 pixels is respected.

**Regression Test (how to make sure this PR doesn't break old functionality)**
Check that resize and column add/remove/toggle works as expected

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by kevinsperrine — APPROVED** [review]

File: packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js [hunk 1]
```diff
@@ -245,6 +244,28 @@ export const adjustLastColumnWidth = (ordering, columns, measuredWidths) => {
...
+ * When the browser layout engine sets the widths dynamically we need to to make
+ * some adjustments to the last column width and also to column widths below
+ * the allowed minimum.
+ * @param {*} ordering
+ * @param {*} columns
+ * @param {*} measuredWidths
+ */
+export const adjustInitialColumnWidths = (ordering, columns, measuredWidths) => {
+  // If the table isn't wide enough for all columns that has a defined width
+  // the browser will will shrink the last column instead of keeping its defined width.
```
Comment (davidicus) [inline packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js:259]: some typo of the double "will"

**Review by davidicus — APPROVED** [review]
