### PR TITLE
Iot progress indicator

### LINKED ISSUE #1116: [ProgressIndicator] Storybook addon toggles don't work in story
[Internal Watson-IoT/pal-tracking#391](https://github.ibm.com/Watson-IoT/pal-tracking/issues/391)

### Describe the bug

Since the latest carbon upgrade [`v10.7.3`]the toggles for "showLabels" and "isVerticalMode" in storybook addons for ProgressIndicator have no effect on the stateful example.

### To Reproduce

1. Go to 'ProgressIndicator'
2. Click on 'Stateful'
3. Enable the addons panel if you have not done so
4. Click on either "showLabels" or "isVerticalMode"

### Expected behavior

- When "showLabels" is unticked, all the Step labels of ProgressIndicator are hidden except for the current Step.
- When "isVerticalMode" is ticked, the ProgressIndicator is displayed in vertical view similar to "presentation vertical" in storybook.

### Environment/versions:

- OS: [MacOS]
- Browser: [chrome]
- `carbon-addons-iot-react` version: [`v2.71.1`]

### Additional context
This issue was not observed at least prior to the carbon upgrade.

Screenshot 2020-04-23 at 21 03 57

### PR DESCRIPTION
**Pull request by rawa-resul**
Closes #1116 #1074

**Summary**

- The new design of the progress indicator based on @lukefirth design from [here](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/progressindicator/overview/)

_Vertical view & RTL_
Screenshot 2020-07-07 at 09 57 37
Screenshot 2020-07-07 at 09 58 12

_Horizontal view & RTL_
Screenshot 2020-07-07 at 09 57 52 Screenshot 2020-07-07 at 09 58 04

_Completed steps with checkmarks_
Screenshot 2020-07-07 at 09 59 34

_Integrated into PageWizard_
Screenshot 2020-07-07 at 09 58 28
Screenshot 2020-07-07 at 09 58 43

**Change List (commits, features, bugs, etc)**

- Created a new ProgressIndicator component using functional rather than class component with backwards compatability
- Created a new ProgressStep component that supports the new styles & svgs
- Supports a new data structure for list items that can incorporate child elements acting as sub elements
- Main steps now show numbers in the icons
- Disabled steps can not be accessed and will be skipped
- Error/Warning steps can be accessed
- Added new prop `clickable` that removes clicking property from the steps (disabling them) - by default to false
- Removed `Styled` functions completely
- Added, Removed, Changed various test cases around the new progress indicator to adhere to new functionality
- Added new prop in PageWizardStep: `subStep` to declare sub steps

**Improvement suggestions**
- I was not able to implement the truncate/ellipsis and tooltip successfully because of width issues in vertical/horizontal view of the labels - it would be great if someone could look into that
- The icons we use in carbon add an invisible border I could not remove. Ideally we dont want this border so that the line sticks directly to the icon
- Currently it does not support passing down of ProgressStep components as children. You would need the items array. 
- Needs a new Skeleton that matches the new design

**Acceptance Test (how to verify the PR)**

- Go to Storybook and click on ProgressIndicator
- Go through the various stories and check that everything works
- Additionally, test the props such as clickable, showlabels, stepWidth and RTL
- Do the same in PageWizard
- Additionally, check that in PageWizard with validation you cannot move to the next step in the progress indicator unless form condition is satisfied. 
- Do the same in TableDetailWizard

### CODE REVIEW

File: src/components/PageWizard/StatefulPageWizard.jsx [hunk 1]
```diff
@@ -76,23 +76,48 @@ const StatefulPageWizard = ({
...
+          return steps[idx];
+        }
+      } else {
+        return undefined;
+      }
+    }
+  };
+
+  const nextStep = getAvailableStep();
+  const prevStep = getAvailableStep(true);
```
Comment (tay1orjones) [inline src/components/PageWizard/StatefulPageWizard.jsx:101]: This signature is a bit confusing. Maybe the index should be the param?

```
  const nextStep = getAvailableStepAtIndex(currentStepIndex + 1);
  const prevStep = getAvailableStepAtIndex(currentStepIndex - 1);
```

File: src/components/PageWizard/PageWizard.jsx [hunk 2]
```diff
@@ -52,6 +52,8 @@ export const PageWizardPropTypes = {
   isProgressIndicatorVertical: PropTypes.bool,
   /** Content to render before footer buttons (on left side, in LTR) */
   beforeFooterContent: PropTypes.node,
+  /** Make the ProgressIndicator clickable */
+  clickable: PropTypes.bool,
```
[the remark this answers is not in the document]
Comment (rawa-resul) [reply src/components/PageWizard/PageWizard.jsx]: Thanks Taylor, I just made this change. All `clickable` props should be `isClickable` now.

File: src/components/PageWizard/StatefulPageWizard.jsx (hunk 1 above)
Comment (rawa-resul) [reply src/components/PageWizard/StatefulPageWizard.jsx:101]: yeah you are right. I changed it by created two simpler/shorter functions for nextStep and prevStep

File: src/components/PageWizard/PageWizard.jsx [hunk 3]
```diff
@@ -1,8 +1,8 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import { ProgressIndicator, ProgressStep } from 'carbon-components-react';
-import classnames from 'classnames';
+import classNames from 'classnames';
```
Comment (davidicus) [inline src/components/PageWizard/PageWizard.jsx:3]: Does this not trigger a lint warning. I think we have a lint rule to standardize these imports to only use `classnames`

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 4]
```diff
@@ -1,82 +1,306 @@
...
+  }
+
+  .line {
+    position: absolute;
+    flex: 1 1 auto;
+    width: calc(100% - 24px);
+    height: 2px;
+    background-color: #e0e0e0;
+    top: 11px;
+    left: 24px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:56]: we shouldn't have any px values

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 5]
```diff
@@ -1,82 +1,306 @@
...
+  }
 
-    .#{$prefix}--progress-optional {
-      margin-left: $spacing-08;
+  .step-button {
+    display: flex;
+    position: relative;
+    text-align: left;
+    width: 8rem;
+    height: 68px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:80]: no pixel values

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 6]
```diff
@@ -1,82 +1,306 @@
...
+  .hidden {
+    visibility: hidden;
   }
 
-  .#{$prefix}--progress-step svg {
-    margin-left: $spacing-03;
-    margin-right: $spacing-03;
+  .sub-step {
+    .icon {
+      margin-top: 4px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:123]: can this be a standard carbon token?

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 7]
```diff
@@ -1,82 +1,306 @@
...
+      margin-left: 0;
+    }
   }
 
-  .#{$prefix}--progress-line {
-    top: 0;
+  svg text {
+    font-size: 18px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:129]: no pixel values

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 8]
```diff
@@ -1,82 +1,306 @@
...
-}
 
-.#{$prefix}--progress-line {
-  width: 100%;
-}
+  //-------States
+
+  .step-current {
+    &:not(.step-invalid) {
+      .main-step {
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:136]: Not sure if these are new classes but we should be using BEM syntax to create these 
```
.#{$prefix}--progress-line-step
.#{$prefix}--progress-line-step__current
.#{$prefix}--progress-line-step__invalid
etc. 
```

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 9]
```diff
@@ -1,82 +1,306 @@
...
+        fill: #0f62fe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:137]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 10]
```diff
@@ -1,82 +1,306 @@
...
+
+        text {
+          fill: white;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:140]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 11]
```diff
@@ -1,82 +1,306 @@
...
+        }
+      }
 
-.#{$prefix}--skeleton {
-  .#{$prefix}--progress-step {
-    flex: unset;
+      .sub-step {
+        svg {
+          fill: #0f62fe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:146]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 12]
```diff
@@ -1,82 +1,306 @@
...
+
+        text {
+          fill: white;
+        }
+      }
 
-.#{$prefix}--skeleton {
-  .#{$prefix}--progress-step {
-    flex: unset;
+      .sub-step {
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:144]: same comment on class naming convention. Should follow BEM as outlined in Carbon repo

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 13]
```diff
@@ -1,82 +1,306 @@
...
-}
 
-html[dir='rtl'] {
-  .#{$iot-prefix}--progress-indicator {
-    &.#{$prefix}--progress--vertical {
-      .#{$prefix}--progress-step-button {
-        text-align: right;
+  .step-complete {
+    svg {
+      fill: #0f62fe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:154]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 14]
```diff
@@ -1,82 +1,306 @@
...
+    }
+  }
+
+  .step-incomplete {
+    .main-step {
+      fill: #171717;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:160]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 15]
```diff
@@ -1,82 +1,306 @@
...
+    }
+
+    .sub-step {
+      svg {
+        color: #171717;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:165]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 16]
```diff
@@ -1,82 +1,306 @@
...
+      }
+    }
+  }
+
+  .step-disabled {
+    &:not(.step-invalid) {
+      .main-step {
+        fill: #bebebe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:173]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 17]
```diff
@@ -1,82 +1,306 @@
...
       }
-      .#{$prefix}--progress-optional {
-        margin-right: $spacing-08;
+
+      .sub-step {
+        svg {
+          fill: #bebebe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:178]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 18]
```diff
@@ -1,82 +1,306 @@
...
       }
     }
 
-    .#{$prefix}--progress-optional {
-      margin-right: $spacing-07;
-      right: 0;
-      margin-left: 0;
+    &.step-invalid {
+      svg {
+        fill: #bebebe;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:185]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 19]
```diff
@@ -1,82 +1,306 @@
...
+      }
+    }
+
+    .label {
+      @extend .label;
+      color: #c6c6c6;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:191]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 20]
```diff
@@ -1,82 +1,306 @@
...
+      cursor: default !important;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:192]: we should not have `!important`. If higher specificity is needed it should be gradually raised through higher specificity .

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 21]
```diff
@@ -1,82 +1,306 @@
...
+      box-shadow: none !important;
+    }
+  }
+
+  .step-invalid {
+    svg {
+      fill: #dd3b41;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:199]: should be using carbon tokens

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 22]
```diff
@@ -1,82 +1,306 @@
...
-    .#{$prefix}--progress-line {
+    .label-container {
       right: 0;
-      left: unset;
+      text-align: right;
+    }
+
+    .line {
+      left: 0;
+      right: 24px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:227]: no pixel values

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 23]
```diff
@@ -1,82 +1,306 @@
...
+      text-align: right;
+
+      &-sub {
+        left: 0;
+        right: 16px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:232]: no pixel values

File: src/components/ProgressIndicator/_progress-indicator.scss [hunk 24]
```diff
@@ -1,82 +1,306 @@
...
+    display: block;
+  }
+
+  .label {
+    position: relative;
+    font-family: $IBMPlexSans;
+    font-size: 14px;
+    color: #161616;
+    letter-spacing: 0.16px;
+    line-height: 18px;
```
Comment (davidicus) [inline src/components/ProgressIndicator/_progress-indicator.scss:28]: the site is down so I can't confirm but there may be a carbon text mixin that we should be using here.

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 25]
```diff
@@ -1,141 +1,362 @@
...
+    return (
+      <span className="icon" title={description}>
+        {value}
+      </span>
+    );
+  };
+
+  const StepLine = () => {
+    const classes = classnames({
+      [`line`]: !complete && !subStep,
```
Comment (davidicus) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:104]: classes will all need a prefix and should follow the BEM syntax as outlined in Carbon repo

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 26]
```diff
@@ -1,141 +1,362 @@
...
+      [`line-complete`]: complete && !subStep,
+      [`line-sub-complete`]: complete && subStep,
+    });
+
+    return !lastItem ? <div className={classes} /> : null;
+  };
+
+  const StepLabel = () => {
+    const classes = classnames({
+      [`label`]: mainStep || subStep,
```
Comment (davidicus) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:115]: Same comment about the classes

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 27]
```diff
@@ -1,141 +1,362 @@
...
+    return (
+      <p className={classes} value={description}>
+        {label}
+      </p>
+    );
+  };
+
+  const StepSecondaryLabel = () => {
+    const classes = classnames({
+      [`label-optional`]: mainStep || subStep,
```
Comment (davidicus) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:128]: same comment about the class naming convention

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 28]
```diff
@@ -1,141 +1,362 @@
...
+            <StepLabel />
+            <StepSecondaryLabel tabIndex="-1" />
+          </div>
+        </button>
+      </>
+    );
+  };
+
+  const classes = classnames({
+    [`step-current`]: current && !disabled,
```
Comment (davidicus) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:173]: prefixes and BEM styled class names

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 29]
```diff
@@ -1,141 +1,362 @@
...
+  incomplete: PropTypes.bool,
+  mainStep: PropTypes.bool,
+  subStep: PropTypes.bool,
+};
+
+ProgressStep.defaultProps = {
+  label: null,
+  secondaryLabel: null,
+  description: null,
+  onChange: null,
```
Comment (davidicus) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:212]: we should use our default function so component does not blow up if no `onChange` is provided.

Comment (tay1orjones) [reply src/components/ProgressIndicator/ProgressIndicator.jsx:212]: Or nullcheck before calling the function https://github.com/IBM/carbon-addons-iot-react/issues/1401

File: src/components/PageWizard/PageWizard.jsx (hunk 3 above)
Comment (tay1orjones) [reply src/components/PageWizard/PageWizard.jsx:3]:
```suggestion
import classnames from 'classnames';
```

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 30]
```diff
@@ -1,141 +1,362 @@
...
+
+  const hasItems = () => newItems.length > 1;
+
+  const classes = classnames({
+    [`${iotPrefix}--progress-indicator`]: true,
+    [`${iotPrefix}--progress-indicator--vertical`]: isVerticalMode,
+    [className]: className,
+  });
+
+  return hasItems() ? (
```
Comment (tay1orjones) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:297]: `hasItems()` seems like an unnecessary abstraction

File: src/utils/__tests__/__snapshots__/publicAPI.test.js.snap [hunk 31]
```diff
@@ -3227,13 +3239,19 @@ Map {
   },
   "ProgressIndicator" => Object {
     "defaultProps": Object {
+      "className": null,
       "currentItemId": null,
+      "isClickable": false,
       "isVerticalMode": false,
-      "onClickItem": null,
```
Comment (tay1orjones) [inline src/utils/__tests__/__snapshots__/publicAPI.test.js.snap:3232]: Removing props is a breaking change. Can we leave it in, put a deprecation notice, and map it to a new prop?

File: src/utils/__tests__/__snapshots__/publicAPI.test.js.snap [hunk 32]
```diff
@@ -3268,19 +3295,24 @@ Map {
...
+                },
               },
             ],
             "type": "shape",
           },
         ],
-        "isRequired": true,
         "type": "arrayOf",
       },
-      "onClickItem": Object {
```
Comment (tay1orjones) [inline src/utils/__tests__/__snapshots__/publicAPI.test.js.snap:3283]: Same thing here on this prop - we're avoiding breaking changes right now

**Comment by tay1orjones** [comment]
@lukefirth @dianatran18 this looks visually correct to me, but would you mind doing a quick review to ensure we look good here?

[Interactive stories for review can be found here](https://deploy-preview-1369--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-progressindicator--stateful)

File: src/components/ProgressIndicator/_progress-indicator.scss (hunk 6 above)
Comment (rawa-resul) [reply src/components/ProgressIndicator/_progress-indicator.scss:123]: I will change it to $spacing-02

**Comment by rawa-resul** [comment]
> Should the focus and active states for adjoining steps be influencing one another? When I have an item selected and then hover over the next/previous, it increases the line below the initial item
> 
> Jul-14-2020 16-44-37
> 
> @lukefirth @dianatran18 what's the desired focus/active states here with this interaction?

I have changed the focus to this:
focus and hover

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 33]
```diff
@@ -1,141 +1,364 @@
...
+    [`${iotPrefix}--progress-indicator`]: true,
+    [`${iotPrefix}--progress-indicator--vertical`]: isVerticalMode,
+    [className]: className,
+  });
+
+  return newItems.length > 1 ? (
+    <ul
+      className={classes}
+      data-testid={`${iotPrefix}--progress-indicator-testid`}
+      onChange={onClickItem || handleChange}
```
Comment (tay1orjones) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:297]: To preserve the original signature of this we need to call `onClickItem` with the `onClickItem(items[index].id);`, correct?

File: src/components/ProgressIndicator/ProgressIndicator.test.jsx [hunk 34]
```diff
@@ -1,22 +1,43 @@
...
-    // click the next step
-    wrapper.find('[tabIndex=0]').simulate('click');
-    expect(mockOnClickItem).toHaveBeenCalledWith('myid2');
-  });
-  it('if click item is not set it still works', () => {
-    const wrapper = mount(<ProgressIndicator items={mockItems} />);
-    // click the next step
-    wrapper.find('[tabIndex=0]').simulate('click');
-    expect(wrapper).toBeDefined();
-  });
```
Comment (tay1orjones) [inline src/components/ProgressIndicator/ProgressIndicator.test.jsx:21]: I think this should be left in until we remove the `onClickItem `

File: src/components/ProgressIndicator/ProgressIndicator.jsx [hunk 35]
```diff
@@ -1,141 +1,364 @@
...
+      invalid: PropTypes.bool,
+    })
+  ),
+  currentItemId: IDPropTypes,
+  showLabels: PropTypes.bool,
+  stepWidth: PropTypes.number,
+  isVerticalMode: PropTypes.bool,
+  isClickable: PropTypes.bool,
+  setStep: PropTypes.func,
+  onClickItem: PropTypes.func,
```
Comment (tay1orjones) [inline src/components/ProgressIndicator/ProgressIndicator.jsx:349]: I believe this prop is effectively deprecated, right? Could we add a deprecation warning to this component about this prop?

We have a helper for it:

https://github.com/IBM/carbon-addons-iot-react/blob/4d14293cc189abf9d222a11d0c5327cc347d0e00/src/components/PageTitleBar/PageTitleBar.jsx#L18-L21

File: src/components/ProgressIndicator/ProgressIndicator.jsx (hunk 33 above)
Comment (rawa-resul) [reply src/components/ProgressIndicator/ProgressIndicator.jsx]: No, by default the progress step onclick event will return the id instead of the index. Before we had a function called handleChange that would use items[index].id and pass it on to the callback function. But I have skipped that part as I am directly passing the id from the progress step.

File: src/components/ProgressIndicator/ProgressIndicator.jsx (hunk 35 above)
Comment (rawa-resul) [reply src/components/ProgressIndicator/ProgressIndicator.jsx:343]: I have added the onClickItem prop back. No need to deprecate it. I made some minor refactoring.

**Comment by dianatran18** [comment]
> > Should the focus and active states for adjoining steps be influencing one another? When I have an item selected and then hover over the next/previous, it increases the line below the initial item
> > Jul-14-2020 16-44-37
> > @lukefirth @dianatran18 what's the desired focus/active states here with this interaction?
> 
> I have changed the focus to this:
> focus and hover

I double checked to see what the Carbon team was doing for their progress indicator. On hover, the text should turn the link (blue) color, and there should be a 1px underline. The focus state should be the same, but with a 3px underline.

The code here is correct: https://react.carbondesignsystem.com/?path=/story/progressindicator--default

Screen Shot 2020-07-21 at 9 24 36 AM

File: src/components/ProgressIndicator/ProgressIndicator.test.jsx (hunk 34 above)
Comment (rawa-resul) [reply src/components/ProgressIndicator/ProgressIndicator.test.jsx:21]: I have added the handleChange test back although adjusted it to use screen now and the other test is actually being tested with one of the other ones I already had in there.

**Comment by rawa-resul** [comment]
> > > Should the focus and active states for adjoining steps be influencing one another? When I have an item selected and then hover over the next/previous, it increases the line below the initial item
> > > Jul-14-2020 16-44-37
> > > @lukefirth @dianatran18 what's the desired focus/active states here with this interaction?
> > 
> > 
> > I have changed the focus to this:
> > focus and hover
> 
> I double checked to see what the Carbon team was doing for their progress indicator. On hover, the text should turn the link (blue) color, and there should be a 1px underline. The focus state should be the same, but with a 3px underline.
> 
> The focus and active states shouldn't be influencing each other either.
> 
> The code here is correct: https://react.carbondesignsystem.com/?path=/story/progressindicator--default
> 
> Screen Shot 2020-07-21 at 9 24 36 AM

I refactored the css again and followed the original css file from carbon [here](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/progress-indicator/_progress-indicator.scss)
