### PR TITLE
fix(tablecardformcontent): remove duplicate thresholds

### LINKED ISSUE #3609: [TableCardFormContent] Duplicate thresholds after editing data series in data table card
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Thresholds are duplicated after editing column thresholds in Customize Data Series dialog.

### To Reproduce

1. Go to Setup page in Monitor;
2. Find an device type;
3. Click on Setup device type;
4. Select Dashboards tab;
5. Create a dashboard;
6. Add Data table card type;
7. Add a column;
8. Click on `edit` button of the new column;
9. Add threshold and save it;
10. Click **again** on `edit` button;
11. See error

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

No duplicated thresholds should be created.

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.151.0-next.44

### Additional context

image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

I will be working in the fix of this issue.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by vaffonso**
Closes #3609

**Summary**

- Remove thresholds of edited column from outer context.

**Change List (commits, features, bugs, etc)**

- TableCardFormContent

**Acceptance Test (how to verify the PR)**

Go to Setup page in Monitor;
Find an device type;
Click on Setup device type;
Select Dashboards tab;
Create a dashboard;
Add Data table card type;
Add a column;
Click on edit button of the new column;
Add threshold and save it;
Click again on edit button;

Check no duplicate threshold added to list

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx [hunk 1]
```diff
@@ -230,8 +230,18 @@ const TableCardFormContent = ({
...
+        card?.content?.columns
+          ?.filter((column) => column?.thresholds?.length)
+          ?.map((column) => column.dataSourceId) || [];
+
+      // Consider existing thresholds outside columns and filter existing thresholds from edited column
+      const allThresholds =
+        thresholds
+          ?.filter(({ dataSourceId }) => !columnThresholdDataSource.includes(dataSourceId))
+          ?.map((threshold) => ({ ...threshold })) || [];
+
```
Comment (herleraja) [inline packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx:244]: dataSourceId is not unique. because you can create threshold with same dataSourceId and different comparison (<, > = ).

**Review by herleraja — CHANGES_REQUESTED** [review]
Need changes.

File: packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx (hunk 1 above)
Comment (vaffonso) [reply packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx:244]: @herleraja it is considered in the code. Existing records in thresholds(content.thresholds) from the same datasourceid are going to be replaced by the new records(colum.thresholds), which contains all current thresholds.

The code above discards thresholds from the column that is being edited (using datasourceid) and re-insert the set of thresholds which is updated to last change.

**Review by herleraja — APPROVED** [review]
LGTM

**Comment by EdmondCShaffer** [comment]
LGTM.  Please add how to test this bug on PAL.

**Review by davidicus — APPROVED** [review]
I was able to figure out how to test but in the future please make sure your reproduction steps are for the PAL storybook. We do not all have access to the monitor repository or application.
