### PR TITLE
fix(resourcelist): convert style component to scss

### LINKED ISSUE #3312: [ResourceList] Convert styled-components to scss
We need to remove styles that are done using styled components and remove the package as a dependency. It may make sense to do a local visual snapshot with Cypress before removal to tell if we are introducing any regressions. Concentrate on deprecated components and stories last.

### PR DESCRIPTION
**Pull request by Ritu-Thakur**
Closes #3312 

**Summary**

convert style component to scss fro Resourcelist

**Change List (commits, features, bugs, etc)**

- added new scss file
- removed 3 style components from Resourcelist

**Acceptance Test (how to verify the PR)**

- tests here

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/ResourceList/ResourceList.jsx [hunk 1]
```diff
@@ -158,7 +118,9 @@ class ResourceList extends Component {
             <Fragment>
               <div className={`${prefix}--structured-list-td`}>
                 <strong>{title}</strong>
-                <InlineDiv className={`${prefix}--structured-list-td`}>{description}</InlineDiv>
+                <div className={`${iotPrefix}--inline-div ${prefix}--structured-list-td`}>
```
Comment (bjornalm) [inline packages/react/src/components/ResourceList/ResourceList.jsx:121]: We might wanna name it
`${iotPrefix}--resource-list__inline-div`
where `resource-list` is the iot specific Block and `inline-div` is the element

File: packages/react/src/components/ResourceList/ResourceList.jsx [hunk 2]
```diff
@@ -192,16 +154,17 @@ class ResourceList extends Component {
     });
 
     return (
-      <ResourceListSection
+      <section
         data-testid={testId}
         className={[
+          `${iotPrefix}--structured-list`,
```
Comment (bjornalm) [inline packages/react/src/components/ResourceList/ResourceList.jsx:160]: Perhaps call this `${iotPrefix}--resource-list` ?

File: packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot [hunk 3]
```diff
@@ -198,14 +198,14 @@ exports[`Storybook Snapshot tests and console checks Storyshots 1 - Watson IoT/R
...
-          className="bx--structured-list-td bx--structured-list-content--nowrap ResourceList__CustomActionDiv-sc-27rnbq-2 gHaTLR"
+          className="bx--structured-list-td bx--structured-list-content--nowrap"
           role="presentation"
         >
           <button
             aria-describedby={null}
             aria-pressed={null}
             className="iot--btn bx--btn bx--btn--ghost"
-            data-testid="resource-list-custom-action-row-0"
+            data-testid="resource-list-custom-action-[object Object]"
```
Comment (bjornalm) [inline packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot:208]: the  [object Object] seems wrong

File: packages/react/src/styles.scss [hunk 4]
```diff
@@ -149,7 +149,7 @@ $deprecations--message: 'Deprecated code was found, this code will be removed be
 @import 'components/PaginationNav/pagination-nav';
 @import 'components/UIShell/ui-shell';
 @import 'components/List/carbon-list';
-@import 'components/Table/TableBody/TableBodyLoadMoreRow/table-body-load-more-row';
+@import 'components/ResourceList/resourcelist';
```
Comment (bjornalm) [inline packages/react/src/styles.scss:152]: Why is the `components/Table/TableBody/TableBodyLoadMoreRow/table-body-load-more-row` removed`?

**Review by bjornalm — CHANGES_REQUESTED** [review]

**Review by bjornalm — COMMENTED** [review]
Nice work, just a couple small changes needed

File: packages/react/src/styles.scss (hunk 4 above)
Comment (Ritu-Thakur) [reply packages/react/src/styles.scss:153]: Fixed it.

File: packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot (hunk 3 above)
Comment (Ritu-Thakur) [reply packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot:208]: It's done automatically. DO you know how to fix it?

File: packages/react/src/components/ResourceList/ResourceList.jsx (hunk 2 above)
Comment (Ritu-Thakur) [reply packages/react/src/components/ResourceList/ResourceList.jsx]: Fixed

File: packages/react/src/components/ResourceList/ResourceList.jsx (hunk 1 above)
Comment (Ritu-Thakur) [reply packages/react/src/components/ResourceList/ResourceList.jsx]: Fixed

**Comment by Ritu-Thakur** [comment]
@bjornalm Needed your input on one of the above comments.

File: packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot (hunk 3 above)
Comment (bjornalm) [reply packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot:208]: The snapshot is updated automatically but the problem comes from the fact that at some point we are adding an object instead of the row-id to the string that makes up the data-testid. This might happen on a higher level where the data-testid is a prop called `testId` or `testID`...

Comment (Ritu-Thakur) [reply packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot]: Fixed

**Comment by Ritu-Thakur** [comment]
@bjornalm Fixed the object issue too.

**Review by kevinsperrine — APPROVED** [review]
Thanks, @Ritu-Thakur!

**Review by davidicus — APPROVED** [review]
