### PR TITLE
fix(dashboardeditor): fixed issue when removing image from image card

### LINKED ISSUE #3672: [DashboardEditor] Deleting image from an image card doesn't remove it from state
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Dashboard editor > Image card - adding an image to be uploaded and then deleting it doesn't actually remove it from dashboardEditor state, only from card json. Even after selecting another image, the old one is also in the state, so when saving changes for the dashboard, there will be 2 api calls for uploading both images.

### To Reproduce

Steps to reproduce the behaviour:

1. Dashboard editor > Add image card > Drag or click to upload new image > Select an image with an invalid name eg. `image$copy.png`
2. Click **Save and close** on top of the dashboard > Error will be displayed because of invalid image name, this is normal
3. Now remove image from card > select another one > click **Save and close** again, same error will be displayed because the old image is still in the dashboardEditor state, specifically in **imagesToUpload**
 - also in the browser Network tab there will be 2 api calls when saving changes, one for each of the images
 - same thing happens when removing the image card and creating a new one, old images will still be there in the state

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Removing an image from an image card OR deleting the image card altogether should remove images completely and prevent them from attempting to be uploaded

### Environment/versions:

- OS: MacOS
- Browser: Chrome, Firefox
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

Monitor issue https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/4491

5d280880-2231-11ed-879b-7de5bd5da736
bee87280-2231-11ed-9b5a-2721faebca54

### PR DESCRIPTION
**Pull request by cosminclinciu1**
Closes #3672

**Summary**

- Fixed issue when removing image from image card

**Change List (commits, features, bugs, etc)**

- [fix(dashboardeditor): fixed issue when removing image from image card](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3673/commits/b1164c7deb001ae4a0c55cc0ab3e221d29776455)

**Acceptance Test (how to verify the PR)**

 - Dashboard editor > Add image card > Drag or click to upload new image > Select an image with an invalid name eg. image$copy.png
 - Click Save and close on top of the dashboard > Error will be displayed because of invalid image name, this is normal
 - Now remove image from card > select another one > click Save and close again > Only new image should be uploaded and the dashboard should save without errors

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by herleraja — APPROVED** [review]
LGTM

File: packages/react/src/components/DashboardEditor/DashboardEditor.jsx [hunk 1]
```diff
@@ -482,6 +482,25 @@ const DashboardEditor = ({
...
+        prevImagesToUpload.filter((image) =>
+          dashboardJsonImages.some(
+            (dashboardImage) => dashboardImage.id === image?.id && dashboardImage.src === image?.src
+          )
+        )
+      );
+    }
+    // this should only execute when dashboardJson is updated; imagesToUpload is not needed as dependency
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [dashboardJson]);
```
Comment (davidicus) [inline packages/react/src/components/DashboardEditor/DashboardEditor.jsx:502]: Do we want a test here? Not sure if that object will trigger a run of this effect.

Comment (davidicus) [reply packages/react/src/components/DashboardEditor/DashboardEditor.jsx:502]: @herleraja?

Comment (herleraja) [reply packages/react/src/components/DashboardEditor/DashboardEditor.jsx:502]: @davidicus do you need an extra test case here or do you want me to test it manually?

**Review by davidicus — APPROVED** [review]
