### PR TITLE
fix(hierarchy-list): uncheck children when parent unchecked

### LINKED ISSUE #3005: [HierarchyList] unchecking parent checkbox does not uncheck children
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Unchecking a parent in the HierarchyList does not uncheck all the children.

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-hierarchylist--with-nested-reorder
2. Change "Editing Style" knob to "multiple-nesting"
3. Check checkbox on "Atlanta Braves"
4. Click chevron to open "Atlanta Braves"
5. Uncheck "Atlanta Braves"
6. All Children of "Atlanta Braves" should now be unchecked, but only the parent was unchecked.

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3005 

**Summary**

- previously when a parent was selected and then unselected, all the children would remain checked. This fixes that.

**Change List (commits, features, bugs, etc)**

- fix onClick being called twice on label and input
- fix locked rows being selected when parent is checked
- fix children not being unselected when parent is unselected
- move the handleSelect call on the checkbox to onChange instead of onClick
- add tests to confirm

**Acceptance Test (how to verify the PR)**

1. https://deploy-preview-3064--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-hierarchylist--with-nested-reorder
2. check a parent
3. uncheck a parent
4. confirm children unselected

1. check a parent with a locked child
2. confirm locked child is not selected

**Regression Test (how to make sure this PR doesn't break old functionality)**

- no adverse effects on other hierarchylist stories

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/List/ListContent/ListContent.jsx [hunk 1]
```diff
@@ -167,7 +167,15 @@ const ListContent = ({
                 name={item.value}
                 data-testid={`${item.id}-checkbox`}
                 labelText=""
-                onClick={() => handleSelect(item.id, parentId)}
+                onClick={(evt) => {
+                  // after the carbon upgrade to 10.47 this event
+                  // is being fired twice, once on the label and once on the
+                  // input, so filtering out the LABEL event here and only firing on
+                  // the input.
+                  if (evt.target.tagName === 'INPUT' && !isLocked) {
```
Comment (kevinsperrine) [inline packages/react/src/components/List/ListContent/ListContent.jsx:175]: The argument could be made this should fire on label and not input. I chose input in this case, because many of our tests are using testIds tied to the checkbox element. Setting this to fire on the label breaks those tests. This is a carbon bug. I've filed an issue. It's re-creatable in their own storybook for the checkbox playground. https://github.com/carbon-design-system/carbon/issues/10122

Comment (kevinsperrine) [reply packages/react/src/components/List/ListContent/ListContent.jsx]: switching this to an onChange seems to be fine and tests all still pass. We need to double check the stories though.

**Comment by bjornalm** [comment]
Code looks good, but I think we should fix the parent child selection relationship properly. For that we also need:
1. When all children are selected, the parent also gets selected.
2. When some, but not all children are selected, set the indeterminate state on the parent.

Checkout the list story at https://deploy-preview-3064--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-list--with-checkbox-multi-selection-and-hierarchy

**Comment by kevinsperrine** [comment]
> Code looks good, but I think we should fix the parent child selection relationship properly. For that we also need:
> 
> 1. When all children are selected, the parent also gets selected.
> 2. When some, but not all children are selected, set the indeterminate state on the parent.
> 
> Checkout the list story at https://deploy-preview-3064--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-list--with-checkbox-multi-selection-and-hierarchy

That's a separate issue: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3066

**Review by davidicus — APPROVED** [review]
