### PR TITLE
fix(bar-chart-card): format x-axis labels to match TimeSeriesCard

### LINKED ISSUE #1572: [BarChartCard] interval='year' formats the axes incorrectly for time-based barChart
### What package is this for?

- [x] React

### Describe the bug

Pass 'year' as the interval prop and notice the x-axis doesn't show the year correctly

image

### LINKED ISSUE #2305: [BarChartCard] xaxis is ignoring the locale property
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
Pass locale french to the Dashboard Editor, notice the x-axis formatting of the line chart uses the correct french months, but the bar chart doesn't

image

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #1572, #2305

**Summary**

Copies necessary formatting methods from TimeSeriesCard into BarChartCard to ensure the x-axis formatting matches those of the TimeSeriesCard

**EDIT**: This PR also fixes #2305 where the locales weren't being respected on the x-axis. I've added locale knobs to the BarChartCard story to confirm this.

**Change List (commits, features, bugs, etc)**

- Adds ticks property to options being passed to the the chart.
- copies formatTick and maxTicksPerSize from TimeSeriesCard

**Acceptance Test (how to verify the PR)**

- I've added a new story to the BarChartCard using time-series data where the number of points and intervals can be changed. As you change intervals from minute, hour, day, month, year. The x-axis label should be formatted the same as it is with TimeSeriesCards.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Other BarChartCards not using time series data should format as they did previously.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
LGTM 👍

File: packages/react/src/components/BarChartCard/BarChartCard.jsx [hunk 1]
```diff
@@ -247,6 +249,49 @@ const BarChartCard = ({
     [categoryDataSourceId, chartData, timeDataSourceId, type, values]
   );
 
+  const previousTick = useRef();
+  dayjs.locale(locale);
+
+  const maxTicksPerSize = useMemo(() => {
```
Comment (bjornalm) [inline packages/react/src/components/BarChartCard/BarChartCard.jsx:255]: nit: perhaps this could be a shared custom hook if it is used in multiple places. Not sure it is worth the trouble..

**Review by bjornalm — APPROVED** [review]
Looks good, but just want to make sure the quarter interval is correct?
image

File: packages/react/src/components/BarChartCard/BarChartCard.jsx (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/BarChartCard/BarChartCard.jsx:255]: I thought about it, but not sure it's worth the time. I think these two places are the only place it's used, and I think, IIRC, the BarChartCard is supposed to replace the TimeSeriesCard at some point, but I could be making that up...

Comment (kevinsperrine) [reply packages/react/src/components/BarChartCard/BarChartCard.jsx:255]: On the quarter interval. I'm honestly not sure. It matches the single date that TimeSeriesCard has, but it could be a bug there, too. @scottdickerson what's the expectation for quarterly intervals?

Comment (davidicus) [reply packages/react/src/components/BarChartCard/BarChartCard.jsx:255]: @scottdickerson any input here?

Comment (davidicus) [reply packages/react/src/components/BarChartCard/BarChartCard.jsx:255]: @kevinsperrine let's fix the conflicts and we will merge this.
