### PR TITLE
fix(table): add align to tooltips

### LINKED ISSUE #3299: [table] column tooltip adds to table-content width
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
When the last column has a tooltip the tooltip will cause the table-content to expand to the right even when the
tooltip is not showing.

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground
2. Click on tab "Column configuration"
3. Enable "Demo column tooltips"

### Expected behavior

The tooltip should not add to the with of the container. 

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context
image

image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by jessieyan**
Closes #3299 

**Summary**

- set align on tooltips
- if last cell, set the align to the opposite 

**Change List (commits, features, bugs, etc)**

- [TableCellRenderer.jsx] added new prop `align`
- [TableHead] added conditions to set `align` on  `TableCellRenderer` component

**Acceptance Test (how to verify the PR)**

Left to right direction
image

Right to left direction
image

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by bjornalm** [comment]
Not sure if this is just a case where the Story and the RTL knob aren't playing nice together but the tooltip of the "last" column in RTL still goes to the right

1. Go to https://deploy-preview-3349--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground
2. enable RTL
3. Enable "Demo column tooltips" 
4. The Tooltip of "String" still goes to the right

File: packages/react/src/components/Table/TableHead/TableHead.jsx [hunk 1]
```diff
@@ -544,6 +553,7 @@ const TableHead = ({
                 truncateCellText={truncateCellText}
                 allowTooltip={false}
                 tooltip={matchingColumnMeta.tooltip}
+                align={isLast ? lastTooltipAlign : align}
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableHead/TableHead.jsx:556]: I think we can use something like 
`tooltipDirection={flipTooltipDirection ? 'start' : undefined}`

**Review by bjornalm — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Table/TableHead/TableHead.jsx (hunk 1 above)
Comment (jessieyan) [reply packages/react/src/components/Table/TableHead/TableHead.jsx:556]: > I think we can use something like `tooltipDirection={flipTooltipDirection ? 'start' : undefined}`

Hello Bjorn,

One question here. Do we allow customizing the tooltip alignment? Previously, it is always set as default which is `start` I  think (we did not pass in the align prop). If so, then I'll only focus on the `rightmostColumn`. Otherwise, we probably need flip the `leftmostColumn`  tooltip if `align` is set to `end`.

Comment (bjornalm) [reply packages/react/src/components/Table/TableHead/TableHead.jsx:556]: For the tooltip in the Table column headers there is no customisation, just the default.

**Comment by jessieyan** [comment]
> 1. https://deploy-preview-3349--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground

Hello Bjorn,

I can see it goes to the left. Any other specifications?  I checked demo tooltips and enabled RTL. 

image

**Review by bjornalm — CHANGES_REQUESTED** [review]
nice work, lets add a unit test for this and we should be good to go

**Comment by jessieyan** [comment]
@bjornalm Added test for tooltips. I was not able to find a good way test directions `ltr` or `rtl`. I can set styles in the dom but not in the browser. `direction` is aways null since it's not in the browser. Do you have any suggestions on this?

**Comment by bjornalm** [comment]
> @bjornalm Added test for tooltips. I was not able to find a good way test directions `ltr` or `rtl`. I can set styles in the dom but not in the browser. `direction` is aways null since it's not in the browser. Do you have any suggestions on this?

I think the `FlyoutMenu.test.e2e.jsx` has some rtl testing. It is browser testing but we can use that.

**Comment by jessieyan** [comment]
> FlyoutMenu

Thanks! I finally found a way to mock up the window object. Now the unit tests work for both 'ltr' and 'rtl'.

**Review by bjornalm — APPROVED** [review]
Nice work
