### PR TITLE
fix(repo): swap styled components to scss

### LINKED ISSUE #1610: [Pull Request Template] add a Regression Test field / question
### What package is this for?

- [x] React
- [x] Angular

### Summary

The current PR template has an Acceptance Test field/question currently that is helpful to remind the dev to give the reader some idea on how to test the PR. I think it would be beneficial (and I've added it myself before)  to have a similar 'Regression Test' field to remind the user to think about how they could have broken old functionality. An example could be:

**Regression Test (how to make sure this PR doesn't break old functionality)**

It doesn't necessarily have to be specific instructions as it could be fully tested for, but it helps to jog the dev's brain

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

N/A

### Available extra resources

What resources do you have to assist this effort?

Can add myself if others think this would be valuable

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1610 
Part of #370 

**Summary**

- Adds a Regression question for PRs
- Swaps styled components from FileDrop, WizardInline, Header, ComposedModal, ComposedStructuredList, ImageCard
- Moved imported style sheets to their respective sections (experimental vs carbon vs addons

**Change List (commits, features, bugs, etc)**

- updated snapshots

**Acceptance Test (how to verify the PR)**

- Go to stories for FileDrop, WizardInline, Header, ComposedModal, ComposedStructuredList, ImageCard and see if anything looks out of place

### CODE REVIEW

File: packages/react/src/components/ComposedStructuredList/ComposedStructuredList.jsx [hunk 1]
```diff
@@ -80,26 +36,38 @@ const StructuredList = ({
     );
   }
   return (
-    <Fragment>
-      <StructuredListWrapperStyled
+    <>
+      <StructuredListWrapper
         {...StructuredListWrapperProps}
+        className={classnames({
+          [`${iotPrefix}--composed-structured-list__wrapper`]: isFixedWidth,
```
Comment (JoelArmendariz) [inline packages/react/src/components/ComposedStructuredList/ComposedStructuredList.jsx:43]: For future implementations, it would probably be better for these one-off class conditions to be set with css variables.

**Review by JoelArmendariz — APPROVED** [review]
LGTM

File: packages/react/src/components/ComposedStructuredList/_composed-structured-list.scss [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    caption-side: bottom;
+    display: table-caption;
+  }
+
+  &__loading {
+    padding-top: $spacing-05;
+  }
+
+  &__list-cell {
+    min-width: var(--width);
```
Comment (davidicus) [inline packages/react/src/components/ComposedStructuredList/_composed-structured-list.scss:26]: these should probably be more descriptive in the future. While I do not think it should have any conflicts since we are defining the value on the component it may be more self documenting if it were to have `list-cell-width` or some such

File: packages/react/src/components/Header/_header.scss [hunk 3]
```diff
@@ -126,3 +126,16 @@ button.#{$prefix}--header__menu-item {
     outline: none;
   }
 }
+
+.#{$iot-prefix}--header--story-test-class {
```
Comment (davidicus) [inline packages/react/src/components/Header/_header.scss:130]: Not sure about shipping styles that are just for the storybook to consumers. We can put these in the storybook css file.

**Review by davidicus — CHANGES_REQUESTED** [review]
Just the one comment on moving the story style to storybook css file.

File: packages/react/src/components/ComposedStructuredList/_composed-structured-list.scss (hunk 2 above)
Comment (sstone2423) [reply packages/react/src/components/ComposedStructuredList/_composed-structured-list.scss:26]: Yep definitely makes sense. This component will be deprecated in the next release as well

File: packages/react/src/components/Header/_header.scss (hunk 3 above)
Comment (sstone2423) [reply packages/react/src/components/Header/_header.scss]: Moved to story scss file

**Review by davidicus — APPROVED** [review]
LGTM
