### PR TITLE
fix(rulebuilder): pad id generator to fix intermittent failing test

### LINKED ISSUE #2040: [RuleBuilder] Race condition in RuleBuilder test
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

A test for a RuleBuilder utility function intermittently fails. 
image

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2040 

**Summary**

- summary_here

**Change List (commits, features, bugs, etc)**

- items_here

**Acceptance Test (how to verify the PR)**

- tests here

### CODE REVIEW

**Review by herleraja — APPROVED** [review]
LGTM

File: packages/react/src/components/RuleBuilder/utils.js [hunk 1]
```diff
@@ -132,7 +132,7 @@ export const getRuleByPath = (arr, path) => {
  */
 export const generateRule = () => {
   return {
-    id: Math.random().toString(36).substring(2, 12),
+    id: Math.random().toString(36).substring(2, 12).padStart(10, '0'),
```
Comment (sstone2423) [inline packages/react/src/components/RuleBuilder/utils.js:135]: This seems unnecessary just to get a test to pass. Maybe its better to remove the length check in the test instead unless you're something specific is happening that makes it need 10 numbers

**Review by sstone2423 — CHANGES_REQUESTED** [review]

File: packages/react/src/components/RuleBuilder/utils.js (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/RuleBuilder/utils.js]: @sstone2423 Good point. Used that approach in newest push.

**Review by sstone2423 — APPROVED** [review]

**Review by davidicus — APPROVED** [review]
