### PR TITLE
fix(repo): Updated hard coded values to use Carbon tokens

### LINKED ISSUE #303: [Repo] Unify Layout, Spacing, and Color to Carbon Tokens
It's been surfaced that there are consistency gaps in these components in regards to layout and spacing.

We should rectify this by 
- [x] Remove hardcoded `margin`, `padding`, etc where possible and use scss/js variables available in `@carbon/layout`
- [x] Remove hardcoded color hex and rgb(a) values, replace with scss/js variables available in `@carbon/colors`
- [x] Add the Carbon Gray 10 theme to our storybook to ensure components adhere to the theme appropriately. We may need to modify some variable names to get the color usage right.

### PR DESCRIPTION
**Pull request by soniadeveloper**
Closes #303 

**Summary**

Replaced hardcoded margin/padding and color values with tokens used in the @carbon/layout and @carbon/colors libraries.

**Change List (commits, features, bugs, etc)**

- Hardcoded values now use carbon tokens

**Acceptance Test (how to verify the PR)**

- Running yarn start on the command line should load the storybook as normal
- Going through component and SCSS files should show that tokens are being used appropriately.

### CODE REVIEW

File: src/components/ImageCard/ImageCard.jsx [hunk 1]
```diff
@@ -13,7 +14,7 @@ import ImageHotspots from './ImageHotspots';
 const ContentWrapper = styled.div`
   height: 100%;
   max-height: 100%;
-  padding: 0 16px 16px 16px;
+  padding: 0 ${spacing05} ${spacing05} ${spacing05};
```
Comment (davidicus) [inline src/components/ImageCard/ImageCard.jsx:17]: can probably leave off the last padding value. I know this was present in the older code.
```suggestion
  padding: 0 ${spacing05} ${spacing05};
```

File: src/components/Page/PageWorkArea.jsx [hunk 2]
```diff
@@ -1,10 +1,11 @@
 import React from 'react';
 import PropTypes from 'prop-types';
 import styled from 'styled-components';
+import { spacing05, spacing07 } from '@carbon/layout';
 
 const StyledDiv = styled.div`
   width: 100%;
-  padding: 2rem 1rem;
+  padding: ${spacing05} ${spacing07};
```
Comment (davidicus) [inline src/components/Page/PageWorkArea.jsx:8]: should these be flipped?
```suggestion
  padding: ${spacing07} ${spacing05};
```

File: src/components/PageWizard/_page-wizard.scss [hunk 3]
```diff
@@ -6,7 +6,7 @@
   display: flex;
 
   &__sticky {
-    padding-bottom: 5rem;
+    padding-bottom: $layout-06;
```
Comment (davidicus) [inline src/components/PageWizard/_page-wizard.scss:9]: this token does not map to 5rem. Have we checked the changes that this would make in the UI?

File: src/components/ResourceList/ResourceList.jsx [hunk 4]
```diff
@@ -30,7 +31,7 @@ const InlineDiv = styled.div`
    {
     font-weight: normal;
     padding-left: 0px !important;
-    padding-top: 5px !important;
+    padding-top: ${spacing02} !important;
```
Comment (davidicus) [inline src/components/ResourceList/ResourceList.jsx:34]: Same here. This token does not map to 5px. What changes to the UI will this cause

File: src/components/Table/TableDetailWizard/TableDetailWizard.jsx [hunk 5]
```diff
@@ -45,9 +46,9 @@ const StyledFooter = styled.div`
 `;
 
 const StyledContentContainer = styled.div`
-  padding-top: 30px;
-  padding-right: 50px;
-  padding-left: 40px;
+  padding-top: ${spacing07};
```
Comment (davidicus) [inline src/components/Table/TableDetailWizard/TableDetailWizard.jsx:49]: Does not map to 30px. Have we checked what the ui implications are here?

File: src/components/Table/TableDetailWizard/TableDetailWizard.jsx [hunk 6]
```diff
@@ -45,9 +46,9 @@ const StyledFooter = styled.div`
...
+  padding-right: ${spacing09};
```
Comment (davidicus) [inline src/components/Table/TableDetailWizard/TableDetailWizard.jsx:50]: Same comment as above. This could cause a break in layout by adding pixels .

File: src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx [hunk 7]
```diff
@@ -20,8 +21,8 @@ const StyledButton = styled.div`
   margin-left: auto;
 
   .bx--btn__icon {
-    margin-left: 5px;
-    margin-right: 5px;
+    margin-left: ${spacing02};
```
Comment (davidicus) [inline src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx:24]: verify that layout does not change.

File: src/components/Table/TableDetailWizard/TableDetailWizardSidebar/TableDetailWizardSidebar.jsx [hunk 8]
```diff
@@ -11,7 +12,7 @@ const StyledDivWizardHeader = styled.div`
   border-right: 1px solid #dadada8c;
 
   .bx--progress {
-    padding: 1rem 1rem 1rem 4rem;
+    padding: ${spacing06} ${spacing06} ${spacing06} ${layout05};
```
Comment (davidicus) [inline src/components/Table/TableDetailWizard/TableDetailWizardSidebar/TableDetailWizardSidebar.jsx:15]: Should this not be spacing05?

File: src/components/Table/_pagination.scss [hunk 9]
```diff
@@ -55,14 +55,14 @@ html[dir='rtl'] {
 
   .#{$prefix}--pagination__right .#{$prefix}--pagination__text {
     margin-left: $spacing-05;
-    margin-right: 0.0625rem;
+    margin-right: $spacing-01 - 0.0625rem;
```
Comment (davidicus) [inline src/components/Table/_pagination.scss:58]: Not quite sure what we are doing here. Looks like you are subtracting the original value from the token. Is this intentional?

File: src/components/Table/_pagination.scss [hunk 10]
```diff
@@ -55,14 +55,14 @@ html[dir='rtl'] {
...
   }
 
   .#{$iot-prefix}--pagination.#{$prefix}--pagination .#{$prefix}--select-input {
     padding: 0 $spacing-05 0 $spacing-08;
 
     @media (min-width: 42rem) {
-      padding-left: 2.25rem;
+      padding-left: $spacing-07 + 0.25rem;
```
Comment (davidicus) [inline src/components/Table/_pagination.scss:65]: Generally if there is not a token that corresponds with a value we should see if it can be changed to a standard size. If not then leaving the rem value is allowed.

File: src/components/TableCard/TableCard.jsx [hunk 11]
```diff
@@ -90,8 +91,8 @@ const StyledStatefulTable = styled(({ showHeader, isExpanded, data, ...rest }) =
       height: 3rem;
 
       th {
-        padding-top: 5px;
-        padding-bottom: 10px;
+        padding-top: ${spacing02};
```
Comment (davidicus) [inline src/components/TableCard/TableCard.jsx:94]: what does this do to layout?

File: src/components/TableCard/TableCard.jsx [hunk 12]
```diff
@@ -90,8 +91,8 @@ const StyledStatefulTable = styled(({ showHeader, isExpanded, data, ...rest }) =
...
+        padding-bottom: ${spacing03 - 2};
```
Comment (davidicus) [inline src/components/TableCard/TableCard.jsx:95]: Same comment as above. There is not need to use a token if you have to add or subtract a value from the token. We should try to standardize or we can leave as is. If there is any question to a UX visual question we can ask it on the #iot-pal slack channel.

File: src/components/TableCard/TableCard.jsx [hunk 13]
```diff
@@ -671,7 +672,7 @@ const TableCard = ({
                       >
                         {item.linkTemplate ? (
                           <>
-                            <p key={`${item.id}-label`} style={{ marginRight: '5px' }}>
+                            <p key={`${item.id}-label`} style={{ marginRight: spacing02 }}>
```
Comment (davidicus) [inline src/components/TableCard/TableCard.jsx:675]: How does this effect layout?

File: src/components/TableCard/TableCard.jsx [hunk 14]
```diff
@@ -684,7 +685,7 @@ const TableCard = ({
                           </>
                         ) : (
                           <>
-                            <p key={`${item.id}-label`} style={{ marginRight: '5px' }}>
+                            <p key={`${item.id}-label`} style={{ marginRight: spacing02 }}>
```
Comment (davidicus) [inline src/components/TableCard/TableCard.jsx:688]: Same comment as above

File: src/components/TableCard/_table-card.scss [hunk 15]
```diff
@@ -1,7 +1,7 @@
 @import '../../globals/vars';
 
 .#{$iot-prefix}--table-card--overflow-menu & {
-  margin-left: 10px;
+  margin-left: $spacing-03;
```
Comment (davidicus) [inline src/components/TableCard/_table-card.scss:4]: This does not map to 10px. What does this do to the layout?

File: src/components/TableCard/_table-card.scss [hunk 16]
```diff
@@ -14,19 +14,19 @@
 
 .#{$iot-prefix}--table-card--action-icon {
   cursor: pointer;
-  margin-left: 11px;
+  margin-left: $spacing-04;
```
Comment (davidicus) [inline src/components/TableCard/_table-card.scss:17]: Same question as above

File: src/components/TableCard/_table-card.scss [hunk 17]
```diff
@@ -14,19 +14,19 @@
...
   &:hover {
     fill: rgb(61, 112, 178);
   }
 }
 
 .#{$iot-prefix}--table-card--expanded-row-content {
-  padding-left: 35px;
-  padding-bottom: 8px;
-  padding-top: 24px;
+  padding-left: $spacing-07;
```
Comment (davidicus) [inline src/components/TableCard/_table-card.scss:24]: Does not map to original value.

File: src/components/TileGallery/_tile-gallery.scss [hunk 18]
```diff
@@ -22,8 +22,8 @@
   .#{$prefix}--content-switcher {
     width: 10rem;
     display: flex;
-    margin-left: 25px;
-    margin-right: 25px;
+    margin-left: $spacing-06;
```
Comment (davidicus) [inline src/components/TileGallery/_tile-gallery.scss:25]: Does not map to original value.

File: src/components/TileGallery/_tile-gallery.scss [hunk 19]
```diff
@@ -22,8 +22,8 @@
...
+    margin-right: $spacing-06;
```
Comment (davidicus) [inline src/components/TileGallery/_tile-gallery.scss:26]: Does not map to original value.

File: src/components/TileGallery/_tile-gallery.scss [hunk 20]
```diff
@@ -152,7 +152,7 @@
       justify-content: center;
       align-items: center;
       background: $ui-02;
-      margin-bottom: 0.9375rem;
+      margin-bottom: $spacing-05;
```
Comment (davidicus) [inline src/components/TileGallery/_tile-gallery.scss:155]: Does not map to original value. Seems awfully specific rem value which may mean a break in layout

File: src/components/ValueCard/_unit-renderer.scss [hunk 21]
```diff
@@ -21,8 +21,8 @@
 }
 
 .#{$iot-prefix}--value-card__attribute-unit--not-wrappable {
-  padding-left: 0.25rem;
-  padding-bottom: 0.8rem;
+  padding-left: $carbon--spacing-02;
```
Comment (davidicus) [inline src/components/ValueCard/_unit-renderer.scss:24]: Why the use of carbon prefix?

File: src/components/ValueCard/_unit-renderer.scss [hunk 22]
```diff
@@ -21,8 +21,8 @@
...
+  padding-bottom: $spacing-03 + 0.05rem;
```
Comment (davidicus) [inline src/components/ValueCard/_unit-renderer.scss:25]: No need to use token this way.

File: src/components/WizardModal/_wizard-modal.scss [hunk 23]
```diff
@@ -7,7 +7,7 @@
 
   .#{$prefix}--progress {
     /* need to pad some space for the focus outlines*/
-    padding: 3px;
+    padding: $spacing-01;
```
Comment (davidicus) [inline src/components/WizardModal/_wizard-modal.scss:10]: Does not map to original value.

File: src/components/WizardModal/_wizard-modal.scss [hunk 24]
```diff
@@ -24,7 +24,7 @@
   .#{$iot-prefix}--wizard-modal__content {
     padding-top: $spacing-05;
     padding-left: $spacing-05;
-    padding-bottom: 7rem;
+    padding-bottom: $layout-06 + 1rem;
```
Comment (davidicus) [inline src/components/WizardModal/_wizard-modal.scss:27]: No need to use tokens in this manner

File: src/components/PageWizard/_page-wizard.scss (hunk 3 above)
Comment (soniadeveloper) [reply src/components/PageWizard/_page-wizard.scss:9]: There's no value that directly maps to 5rem so I may leave this one as an exception

**Comment by tay1orjones** [comment]
For the values that we deem acceptable deviations, we can ignore the disallowed units rule (#1359) per line via:

```
.selector {
  margin: 5px; /* stylelint-disable-line rule-name-here */
}
```

Stylint docs on ignoring lines: https://stylelint.io/user-guide/ignore-code

File: src/components/TileGallery/_tile-gallery.scss (hunk 20 above)
Comment (soniadeveloper) [reply src/components/TileGallery/_tile-gallery.scss:155]: Making an exception for this one 👍

File: src/components/PageWizard/_page-wizard.scss (hunk 3 above)
Comment (soniadeveloper) [reply src/components/PageWizard/_page-wizard.scss:9]: This will not break the layout, so it can be standardized 👍

File: src/components/ResourceList/ResourceList.jsx (hunk 4 above)
Comment (soniadeveloper) [reply src/components/ResourceList/ResourceList.jsx:34]: This will not break the UI, only brings the description slightly closer to the header when resource list design is set to inline so it can be standardized 👍

File: src/components/Table/TableDetailWizard/TableDetailWizard.jsx (hunk 5 above)
Comment (soniadeveloper) [reply src/components/Table/TableDetailWizard/TableDetailWizard.jsx:49]: This will not break the layout so it can be standardized 👍

File: src/components/Table/TableDetailWizard/TableDetailWizard.jsx (hunk 6 above)
Comment (soniadeveloper) [reply src/components/Table/TableDetailWizard/TableDetailWizard.jsx:50]: This one also does not change anything significant 👍

File: src/components/Table/_pagination.scss (hunk 10 above)
Comment (soniadeveloper) [reply src/components/Table/_pagination.scss:65]: This value can be changed to a standard size 👍

**Comment by soniadeveloper** [comment]
All of the values that may not have matched a token in the SCSS were able to be standardized. If not, I left an exception. I left any styling in the JSX files as pixel/rem units since the linters will not pick it up and cause errors.

File: src/components/Page/PageWorkArea.jsx (hunk 2 above)
Comment (tay1orjones) [reply src/components/Page/PageWorkArea.jsx:8]: Yeah these should be flipped @soniadeveloper

File: src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx (hunk 7 above)
Comment (tay1orjones) [reply src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx]: This class is no longer used it appears. The close button receives classes of `bx--btn bx--btn--ghost`

File: jest.config.js [hunk 25]
```diff
@@ -20,12 +20,12 @@ module.exports = {
...
-      branches: 77,
-      lines: 73,
-      functions: 57,
-    },
+    // './src/components/Table/TableHead/TableHead.jsx': {
+    //   statements: 73,
+    //   branches: 77,
+    //   lines: 73,
+    //   functions: 57,
+    // },
```
Comment (tay1orjones) [inline jest.config.js:28]: @soniadeveloper Looks like you might've pushed some unrelated changes here?
