### PR TITLE
fix(table): show correct number of columns in tableskeleton

### LINKED ISSUE #3323: [table] loading state missing column for row nesting
### What package is this for?

- [x] React
- [ ] Angular

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground
2. Click on Tab "Nesting & expansion" and activate knob "Demo nested rows (options.hasRowNesting)"
3. Click on tab "States" and activate knob "Show table loading state (view.table.loadingState.isLoading)"

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

There should be an additional column

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #3323

**Summary**
Fixes the number of columns shown for TableSkeletonWithHeader when `rowNesting` is used

**Change List (commits, features, bugs, etc)**

- Add fix to TableSkeletonWithHeader and Table
- Added unit tests

**Acceptance Test (how to verify the PR)**

1. Go to https://deploy-preview-3326--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--playground
2. Click on Tab "Nesting & expansion" and activate knob "Demo nested rows (options.hasRowNesting)"
3. Click on tab "States" and activate knob "Show table loading state (view.table.loadingState.isLoading)"
4. Make sure the number of columns is correct

**Regression Test (how to make sure this PR doesn't break old functionality)**
1.  TableSkeletonWithHeader works as expected

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx [hunk 1]
```diff
@@ -79,7 +82,7 @@ const TableSkeletonWithHeaders = ({
           className={`${iotPrefix}--table-skeleton-with-headers--table-row`}
         >
           {hasRowSelection === 'multi' ? <TableCell /> : null}
-          {hasRowExpansion ? <TableCell /> : null}
+          {hasRowExpansion || hasRowNesting ? <TableCell /> : null}
           {loadingColumns.map((v, colIndex) => (
             <TableCell key={`emptycell-${colIndex}`}>
               {rowIndex === 0 && !columns.length ? <SkeletonText /> : null}
```
Comment (kevinsperrine) [inline packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx:88]: Might this be a good time to use Shady's SkeletonRow from a couple week ago?

Comment (bjornalm) [reply packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx:88]: I hear you and I started doing that, but realised it would be a slightly bigger refactoring (SkeletonRow is not based on TableRow and there are other small differences with classes etc) than the tiny and safe fix I promised David in order to add this one to the current sprint  :-)

Comment (kevinsperrine) [reply packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx:88]: Ah, got it. No worries! Just wanted to check.

Comment (bjornalm) [reply packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx:88]: We can create another issue to use SkeletonRow here so that it is not forgotten

**Review by kevinsperrine — COMMENTED** [review]
Code all looks good. Still waiting on Netlify to run the preview though.

**Review by kevinsperrine — APPROVED** [review]

File: packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx (hunk 1 above)
Comment (bjornalm) [reply packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx:88]: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3336

**Review by davidicus — APPROVED** [review]

File: packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap [hunk 2]
```diff
@@ -3968,6 +3968,7 @@ Map {
       "columns": Array [],
       "hasRowActions": false,
       "hasRowExpansion": false,
+      "hasRowNesting": false,
```
Comment (davidicus) [inline packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap:3971]: @bjornalm Does this new prop need to be added to our docs?

Comment (bjornalm) [reply packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap:3971]: It already exists in the Table documentation. The `TableSkeletonWithHeaders.jsx` does not have a mdx file or any dedicated documentation at all. But it is exported so perhaps we should create docs for it? I can add an issue to https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2820 if you want
