### PR TITLE
fix(table): aggregation column placement

### LINKED ISSUE #2859: [table] aggregation data placed in wrong columns
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The aggregation column label ends up in the first column which is not wide enough to display any text and the actual sum of data ends up in the incorrect column (to the left of where it suppose to be). 

### To Reproduce

Use the following settings:
```
const tableData = addRowActions(getTableData(20, words, selectData));
    tableData[0].children = [
      { ...tableData[0], id: 'row-0-A' },
      { ...tableData[0], id: 'row-0-B' },
    ];
    tableData[1].children = [
      { ...tableData[1], id: 'row-1-A', children: [{ ...tableData[1], id: 'row-1-A-1' }] },
    ];

    const columnsOverflowMenu = getTableColumns(selectData).map((col) => ({
      ...col,
      align: 'center',
    }));
    columnsOverflowMenu[0].width = '300px';
    columnsOverflowMenu[1].width = `${MIN_COLUMN_WIDTH}px`;
    columnsOverflowMenu[1].isSortable = false;
    columnsOverflowMenu[2].width = `${DEFAULT_COLUMN_WIDTH}px`;

<Table
        testId="snapshot-2"
        columns={columnsOverflowMenu}
        data={tableData}
        useZebraStyles={false}
        lightweight
        options={{
          hasAggregations: true,
          hasColumnSelection: true,
          hasColumnSelectionConfig: false, 
          hasFilter: true,
          hasPagination: true,
          hasResize: true,
          hasRowEdit: false,
          hasRowExpansion: false,
          hasRowActions: false,
          hasRowNesting: true,
          hasRowSelection: 'single',
          hasSearch: true,
          hasSort: true,
          hasSingleRowEdit: true,
          useAutoTableLayoutForResize: false,
          wrapCellText: 'always',
          size: 'md',
          shouldExpandOnRowClick: false,
        }}
        view={{
          aggregations: {
            label: 'Total:',
            columns: [
              {
                id: 'number',
                align: 'center', 
                isSortable: false,
              },
            ],
          },
          pagination: { isItemPerPageHidden: false },
          table: {
            isSelectAllSelected: false,
            selectedIds: ['row-4'],
            expandedIds: ['row-0', 'row-1', 'row-1-A'],
            sort: {
              columnId: 'select',
              direction: 'ASC',
            },
          },
          toolbar: {
            activeBar: 'column',
            search: { defaultExpanded: true },
          },
        }}
      />
```

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

The label "total" should appear in the second column (the string column) and not be wrapped.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2859 

**Summary**

- When using multiselect and nested rows at the same time, the aggregation label was in the wrong place. This fixes that by using colspan to position the label based on various prop combinations.

**Change List (commits, features, bugs, etc)**

- use colspan instead of cells to position label
- add tests to confirm

**Acceptance Test (how to verify the PR)**

- Go to [`basic dumb table` story](https://deploy-preview-2898--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-table--basic-dumb-table)
- turn on pagination
- experiment with all combinations of `hasRowNesting`, `hasRowExpansion`, and `hasRowSelection`. The 'Total' label should also be aligned with the pagination below.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- aggregation placement is still correct on other aggregation stories/settings

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by bjornalm** [comment]
image

To reproduce:
1. Go to basic dumb table story
2. Set table type to StatefulTable
3. enable hasPagination & hasColumnSelection
4. move the number column all the way to the left

**Review by bjornalm — CHANGES_REQUESTED** [review]
See screenshot

**Comment by kevinsperrine** [comment]
> See screenshot

got it. adjusted so it matches next. deploying now.

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx [hunk 1]
```diff
@@ -50,46 +51,59 @@ const defaultProps = {
...
+            <Fragment key="label-cell-fragment">
+              <TableCell
+                className={`${iotPrefix}-table-foot--label`}
+                data-testid={cellTestId}
+                key={cellKey}
+                colSpan={colSpan}
+              >
+                {aggregations.label}
+              </TableCell>
+              {colSpan === 2 && hasMultiSelect && hasExpandOrNest ? (
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableFoot/TableFoot.jsx:83]: Hmm, if either hasMultiSelect or hasExpandOrNest is true, then I don't think we don't need to test for colSpan === 2. But it is also a bit confusing that we calculate the colspan and at the same time introduce a spacer cell that we just merge.  Is that needed?

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx [hunk 2]
```diff
@@ -50,46 +51,59 @@ const defaultProps = {
...
-  options: { hasRowExpansion, hasRowSelection, hasRowActions },
+  options: { hasRowExpansion, hasRowSelection, hasRowActions, hasRowNesting },
   tableState: { aggregations, ordering },
   showExpanderColumn,
 }) => {
   const visibleColumns = ordering.filter((col) => !col.isHidden);
 
+  const hasMultiSelect = hasRowSelection === 'multi';
+  const hasExpandOrNest = hasRowExpansion || hasRowNesting;
+  const colSpan = hasExpandOrNest || hasMultiSelect ? 2 : 1;
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableFoot/TableFoot.jsx:62]: nit: call it labelCellColspan to clarify where we gonna use it?

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/Table/TableFoot/TableFoot.jsx]: sure, I can merge it into the colSpan.

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx [hunk 3]
```diff
@@ -50,46 +51,57 @@ const defaultProps = {
...
 
           return isLabelCell ? (
-            <TableCell
-              className={`${iotPrefix}-table-foot--label`}
-              data-testid={cellTestId}
-              key={cellKey}
-            >
-              {aggregations.label}
-            </TableCell>
+            <Fragment key="label-cell-fragment">
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableFoot/TableFoot.jsx:75]: We can remove the fragment now

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx [hunk 4]
```diff
@@ -50,46 +51,57 @@ const defaultProps = {
...
-              })}
-              align={aggregated.align ? aggregated.align : undefined}
-              data-testid={cellTestId}
-              key={cellKey}
-            >
-              {aggregated.value}
-            </TableCell>
+            <Fragment key={`aggregated-cell-fragment-${index}`}>
+              {index === 0 && (hasMultiSelect || hasExpandOrNest) ? (
+                <TableCell colSpan={hasMultiSelect && hasExpandOrNest ? 2 : 1} />
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableFoot/TableFoot.jsx:88]: nit: this could also be simplified into just to having a single condition to add the extra table cell or not.

**Review by bjornalm — APPROVED** [review]
Nice work, I left two small comments.

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx (hunk 3 above)
Comment (kevinsperrine) [reply packages/react/src/components/Table/TableFoot/TableFoot.jsx:75]: removed.

File: packages/react/src/components/Table/TableFoot/TableFoot.jsx (hunk 4 above)
Comment (kevinsperrine) [reply packages/react/src/components/Table/TableFoot/TableFoot.jsx:88]: given that all of this is going to be reworked to account for aggregations in the first column or potentially multiple labels, I don't really think that's important right now.

**Review by davidicus — APPROVED** [review]
