### PR TITLE
fix(table): add skeleton column for nesting rows when lazy loading

### LINKED ISSUE #3220: [Table] shouldLazyRender renders incorrect columns
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The prop `shouldLazyRender` renders incorrect columns when combined with `options.hasRowNesting` and `options.hasRowSelection:multi

### To Reproduce

1. Go to a playground story
2. Enable shouldLazyRender
3. Enable options.hasRowNesting 
4. Set options.hasRowSelection to "multi"

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3220 

**Summary**

- The placeholder skeleton column was missing when lazy loading with `hasNestedRows`. This fixes that.

**Change List (commits, features, bugs, etc)**

- add check for `hasRowNesting` when including skeleton columns

**Acceptance Test (how to verify the PR)**

- go the the basic table story
- turn on hasRowNesting
- turn on hasRowSelection to 'multi'
- turn on shouldLazyRender
- confirm the columns align with header and Object ID column isn't missing a skeleton

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx [hunk 1]
```diff
@@ -198,7 +198,7 @@ const TableBodyRowRenderer = (props) => {
         data-testid={`${tableId}-lazy-row-${row.id}`}
       >
         {hasRowSelection === 'multi' ? <TableCell /> : null}
-        {hasRowExpansion ? <TableCell /> : null}
+        {hasRowExpansion || hasRowNesting ? <TableCell /> : null}
```
Comment (bjornalm) [inline packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx:201]: We can use the `totalColumns` which contains the number of visible columns prop (calculated by the table and passed down to its subcomponents) and simplify this section by only writing:  

```
  {totalColumns.map((v, colIndex) => (
    <TableCell key={`empty-cell-${colIndex}`}>
      <SkeletonText />
    </TableCell>
  ))}
```

**Review by bjornalm — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx]: I had to add a fix to make `hasRowNesting` add an extra column to the totalColumn count, but otherwise, it's much cleaner. Thanks!

Comment (bjornalm) [reply packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx]: Man I'm sorry. But I was probably wrong here. This would work fine if we were just inserting empty cells for the whole row, but I realise now that only the actual data columns should show skeleton texts. Here all extra spacer columns also get the skeleton:

image

Your original solution was the best option here

Comment (kevinsperrine) [reply packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx:201]: reverted.

**Review by bjornalm — APPROVED** [review]
Nice work!

**Comment by davidicus** [comment]
@Shady-Nessim FYI, this may affect your issue #3190.

**Review by davidicus — APPROVED** [review]
