### PR TITLE
fix(table): fixed late loading

### LINKED ISSUE #1191: [StatefulTable] Can't set totalItems when late loading
### To Reproduce

We are using late loading data in StatefulTable, so at first time, the tabledata sent to StatefulTable is just a part of data, not complete data. 
we want to use totalItems field to specify the real total data count, instead of table data count. However i found totalItems  doesn’t work. 
I found this  https://github.com/IBM/carbon-addons-iot-react/pull/372  seems someone has fixed it but actually still not.
here is my version of carbon-addons-iot-react: 2.62.0

### Expected behavior
When using late loading, we expect to set correct totalItems to do pagination.

### Environment/versions:

- OS: [ MacOS,]
- `carbon-addons-iot-react` version: [ `2.62.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?
Our product will be released in September, so it will be good if can be fix before that timeline.

### PR DESCRIPTION
**Pull request by marcJV**
Closes #1191 

**Summary**

Fixes the stateful table from ignoring totalItems prop

**Change List (commits, features, bugs, etc)**

Added story to show the ability to have a totalItem different than the current dataset size

**Acceptance Test (how to verify the PR)**

Stateful Table with Late load data, click the button and observe

### CODE REVIEW

File: src/components/Table/StatefulTable.jsx [hunk 1]
```diff
@@ -256,7 +261,8 @@ const StatefulTable = ({ data: initialData, expandedData, ...other }) => {
         },
         pagination: {
           ...view.pagination,
-          totalItems: filteredData.length,
+          totalItems:
+            (state.data?.length || 0) === filteredData.length ? totalItems : filteredData.length,
```
Comment (bjornalm) [inline src/components/Table/StatefulTable.jsx:265]: I find this line combined with the totalItems line above really difficult to follow. Is it possible to use some well named constants and restructure this logic to better explain what is going on?

Something along the lines below (I haven't tried it but you get the gist)

```
const filteredCount = filteredData.length;
const paginationCount = state.view.pagination?.totalItems;
const currentlyLoadedDataCount = state.data?.length || 0;

const totalItems = filteredCount && filteredCount !== currentlyLoadedDataCount ? 
  filteredCount  : 
  (paginationCount || currentlyLoadedDataCount);
```

Perhaps this can be simplified further

**Review by bjornalm — CHANGES_REQUESTED** [review]
Nice work. Just a couple of things. Is it possible to create story where the pagination works and still demonstrate the point of this fix?

**Comment by marcJV** [comment]
> Nice work. Just a couple of things. Is it possible to create story where the pagination works and still demonstrate the point of this fix?

This is fixed in the latest, let me know if that is sufficient.

**Review by bjornalm — APPROVED** [review]
Nice work

**Review by davidicus — APPROVED** [review]
