### PR TITLE
fix(tablecardformcontent): discard threshold from columns

### LINKED ISSUE #3563: [TableCardFormContent] Validation expects thresholds attribute to be removed for empty list.
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Invalid JSON after removing the last data item with threshold.

Error:
Value `[]` at .content.thresholds. should NOT have fewer than 1 items.

Error:
Value `"thresholds"` at .content.columns[0]. should be equal to one of the allowed values. Allowed values are label, dataSourceId, destination, priority, filter, type, width, sort, renderDataFunction, linkTemplate.. Value `{"dataSourceId":"timestamp","label":"Timestamp","type":"TIMESTAMP","sort":"DESC","thresholds":[]}` at .content.columns[0]. property name 'thresholds' is invalid.

Screen Shot 2022-09-22 at 16 43 54

### To Reproduce

1. Go to 'Dashboard'
2. Create new dashboard
3. Add 3 data items
4. Add some threshold to the data item (Save the dashboard)
5. Remove the data item that has threshold
6. goto Open JSON editor
7. click save --> now thresholds property getting added to the columns attributes

### Expected behavior

There should be no `thresholds` attribute for empty list.

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.150.0-next

### Additional context
-

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by vaffonso**
Closes #3563
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3389

**Summary**

- Remove threshold attribute for empty threshold lists

**Change List (commits, features, bugs, etc)**

- Remove threshold attribute for empty list from content
- Remove unnecessary threshold attribute from content.columns

**Acceptance Test (how to verify the PR)**

- Go to 'Dashboard'
- Create new dashboard
- Add 3 data items
- Add some threshold to the data item (Save the dashboard)
- Remove the data item that has threshold
- goto Open JSON editor
- Click save 
- No errors displayed.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx [hunk 1]
```diff
@@ -258,6 +259,10 @@ const TableCardFormContent = ({
       const filteredColumns = dataSection.filter(
         (item) => item.dataSourceId !== dataItem.dataSourceId
       );
+      // Filter existing thresholds
+      const filteredThresholds = cardConfig?.content?.thresholds?.filter(
```
Comment (herleraja) [inline packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx:263]: I think you forgot to update the thershold in updatedContent

**Review by herleraja — CHANGES_REQUESTED** [review]
LGTM. One minor update needed.

**Review by herleraja — APPROVED** [review]
LGTM

**Review by EdmondCShaffer — APPROVED** [review]

**Review by davidicus — APPROVED** [review]
