### PR TITLE
fix(suite-header): all cmd+click/ctrl+click to open new window

### LINKED ISSUE #2852: [ui-shell] Open navigation items in new tab
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

There is no way to right-click (or Cmd+click or Ctrl+click) to open a navigation item in a new tab or a new window within the browser.

### To Reproduce

The bug we are seeing is in the IBM TRIRIGA product – our nav items don't allow for opening in a new tab/window.

### Expected behavior

The user will see a list of opens, which include "Open link in new tab" or "Open link in new window" whenever they right click on a navigation item.

### Environment/versions:

- OS: Any
- Browser: Any
- `carbon-addons-iot-react` version:v7.43.0 (latest version)

### Additional context

Screenshot below:
SS  2021-09-17 at 11 52 58 AM

### Specific timeline issues / requests

As soon as possible

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2852 

**Summary**

- Makes it possible to open SuiteHeader links by holding cmd+click or ctrl+click.

**Change List (commits, features, bugs, etc)**

- Adds cmd+click / ctrl+click checking to all built-in SuiteHeader links
- Updates docs to make to more clear how this behavior can be controlled on the application side
- added tests for coverage

**Acceptance Test (how to verify the PR)**

- holding cmd+click (mac) or ctrl+click (win) should open all SuiteHeader links (Administation, Manage Profile, Help, All Applications, Monitor, Health, etc) in a new window.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- links still open in same window when not hold ctrl or cmd.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/SuiteHeader/SuiteHeader.jsx [hunk 1]
```diff
@@ -389,16 +392,21 @@ const SuiteHeader = ({
...
+              const newWindow = shouldOpenInNewWindow(e);
               if (isAdminView) {
                 href = navigatorRoute;
                 routeType = ROUTE_TYPES.NAVIGATOR;
               }
               const result = await onRouteChange(routeType, href);
               if (result) {
-                window.location.href = href;
+                if (newWindow) {
+                  window.open(href, '_blank', 'noopener noreferrer');
```
Comment (bjornalm) [inline packages/react/src/components/SuiteHeader/SuiteHeader.jsx:406]: Nice. I think adding the noopener and noreferrer here makes sense since they are becoming the default when using normal _blank links

File: packages/react/src/components/SuiteHeader/SuiteHeader.jsx [hunk 2]
```diff
@@ -441,10 +449,15 @@ const SuiteHeader = ({
                       'data-testid': 'suite-header-help--about',
                       href: 'javascript:void(0)',
                       title: mergedI18N.about,
-                      onClick: async () => {
+                      onClick: async (e) => {
```
Comment (bjornalm) [inline packages/react/src/components/SuiteHeader/SuiteHeader.jsx:452]: nit: There is code duplication for the onClick functions and it can probably be refactored into a separate function that handles the logic of correctly opening a route.

File: packages/react/src/components/SuiteHeader/SuiteHeader.mdx [hunk 3]
```diff
@@ -218,6 +219,181 @@ import { SuiteHeader } from 'carbon-addons-iot-react';
 />;
 ```
 
+## Opening a route in a new window
+
+The SuiteHeader and SideNav are very versatle. Application developers have control over the elements and metadata used to render a SideNav link or custom actions.
```
Comment (bjornalm) [inline packages/react/src/components/SuiteHeader/SuiteHeader.mdx:224]: Spelling versatile

File: packages/react/src/components/SuiteHeader/SuiteHeader.mdx [hunk 4]
```diff
@@ -218,6 +219,181 @@ import { SuiteHeader } from 'carbon-addons-iot-react';
...
+All of the built-in actions in the SuiteHeader (Administation link, help, profile, or Application Switcher) can be opened in a new window by holding <kbd>⌘</kbd>+<kbd>Left-Click</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>Left-Click</kbd> (Windows).
```
Comment (bjornalm) [inline packages/react/src/components/SuiteHeader/SuiteHeader.mdx:225]: Spelling Administration

**Review by bjornalm — APPROVED** [review]
Nice job as always!

File: packages/react/src/components/SuiteHeader/SuiteHeader.mdx (hunk 3 above)
Comment (kevinsperrine) [reply packages/react/src/components/SuiteHeader/SuiteHeader.mdx]: thanks, fixed.

File: packages/react/src/components/SuiteHeader/SuiteHeader.mdx (hunk 4 above)
Comment (kevinsperrine) [reply packages/react/src/components/SuiteHeader/SuiteHeader.mdx]: thanks, fixed.

File: packages/react/src/components/SuiteHeader/SuiteHeader.jsx (hunk 2 above)
Comment (kevinsperrine) [reply packages/react/src/components/SuiteHeader/SuiteHeader.jsx]: Good call. I extracted this out, and made the tests a little more robust by using different hrefs for all the routes to confirm the correct route was being called and not an accident since they were all just ibm.com.

**Review by davidicus — APPROVED** [review]
