### PR TITLE
fix(table): change tooltips to carbon-like

### LINKED ISSUE #3510: [Table] Use same tooltip style for all tooltips
Use the carbon tooltip style on all hover labels. Working correctly for pagination buttons. Need to update the action buttons (Filter, Search, etc)
Correct:
Screen Shot 2022-07-29 at 9 44 31 AM
Needs update:
Screen Shot 2022-07-29 at 9 44 37 AM

### PR DESCRIPTION
**Pull request by erzhan-temir-mamyrov**
Closes #3510

**Summary**

- Change appearance of tooltips to carbon-like

**Change List (commits, features, bugs, etc)**

- Change `kind` prop in `TableToolbarSVGButton` to enable carbon tooltip in button
- Add i18n for icon description in `TableToolbarAdvancedFilterFlyout`
- Remove native browser tooltips
- Update test selector from `getByTitle` to `getById` or `getByText`
- Create `TableExpandRow` component with Carbon tooltip
- Create `IotOverflowMenu` component with Carbon tooltip
- Update storyshots

**Acceptance Test (how to verify the PR)**

- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground)
- Enable `toolbarAction`, `customToolbarContent`, `Demo download data as CSV` under "Toolbar" knob tab in order to see toolbar action buttons
- Change `hasFilter` value to `true` in "Sort & filter" knob tab to see filter action button
- Hover on the action buttons in table toolbar in order to see carbon tooltips.

</br>

- _Filter icon button_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-filtering)
- Change `hasFilter` value to `true` in knobs to see filter action button
- Hover on the action buttons in table toolbar in order to see carbon tooltips.

</br>

- _Flyout menu and data download icon buttons_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-toolbar)
- Enable `customToolbarContent`, `Demo download data as CSV` in knobs to see toolbar action buttons
- Hover on the action buttons in table toolbar in order to see carbon tooltips.

</br>

- _Row edit icon button_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-data-editing)
- Enable `hasRowEdit` in knobs to see edit button
- Hover on the button in table toolbar in order to see carbon tooltips.

</br>

- _Column selection icon button_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-asynchronous-data-source)
- Hover on the action buttons in table toolbar in order to see carbon tooltips.

</br>

- _Row expansion icon button_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-row-expansion)
- Hover on button to expand row.
- Verify that carbon tooltip has appeared.

</br>

- _Overflow menu icon button_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--with-aggregations)
- Hover on overflow menu.
- Verify that carbon tooltip has appeared.

</br>

- _TableCard_
- Go to [this story](https://deploy-preview-3541--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-dashboard--dashboard-all-cards-as-resizable)
- Enable tooltips in the story knobs.
- Scroll to the `TableCard`
- Hover on the toolbar.
- Verify that table icon-buttons have Carbon tooltip.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by kevinmweaver** [comment]
@erzhan-temir-mamyrov I would use the carbon-style tooltip and have the position be above the arrow at the end of the tooltip like this. 
image

**Comment by sls-ca** [comment]
@kevinmweaver @davidicus @erzhan-temir-mamyrov If we are using the carbon tooltips, then let's verify that they work in RTL mode.  I suspect that carbon accounts for this but let's just verify that when in RTL mode that the tooltips don't flow off the left side of the screen.

**Comment by davidicus** [comment]
When I put the story in to RTL mode, a horizontal scrollbar is created. I also see the tooltip on the overflow menu being rendered off screen in RTL when the custom content knob is not clicked.

**Comment by erzhan-temir-mamyrov** [comment]
@davidicus Thanks for the feedback! I will fix it.

File: packages/react/src/constants/CardPropTypes.js [hunk 1]
```diff
@@ -230,6 +230,8 @@ export const TableCardPropTypes = {
   cardVariables: PropTypes.objectOf(
     PropTypes.oneOfType([PropTypes.string, PropTypes.func, PropTypes.number, PropTypes.bool])
   ),
+  /** Display tooltips in the table toolbar (will reset overflow property) */
+  withToolbarTooltips: PropTypes.bool,
```
Comment (davidicus) [inline packages/react/src/constants/CardPropTypes.js:234]: is this something that can be specific to the TableCard?

**Review by davidicus — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Table/TableBody/TableBodyRow/TableExpandRow.jsx [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+      <TableCell
+        className={`${prefix}--table-expand`}
+        data-previous-value={previousValue}
+        headers={expandHeader}
+      >
+        <Button
+          aria-label={ariaLabel}
+          testId={`expand-icon-button-${rowId}`}
+          className={cx(
+            `${prefix}--btn--icon-only`,
```
Comment (davidicus) [inline packages/react/src/components/Table/TableBody/TableBodyRow/TableExpandRow.jsx:100]: This class is added for this button type so do not have to manually do it here. We should be re-adding the `.${prefix}--table-expand__button` class. You see how it broke our test and you had to fix. It will do the same for any consumers who are using it for selectors in their test.

Comment (davidicus) [reply packages/react/src/components/Table/TableBody/TableBodyRow/TableExpandRow.jsx:100]: This may also allow you to not have to add additional styling and/or classes, if any was added to match the previous button.

File: packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx [hunk 3]
```diff
@@ -30,3 +34,354 @@ describe('OverflowMenu', () => {
...
+      <OverflowMenu testId={testId} withCarbonTooltip>
+        <OverflowMenuItem itemText="Option 1" />
+      </OverflowMenu>
+    );
+
+    expect(baseElement.querySelector('ul')).toBeNull();
+
+    const trigger = screen.getByTestId(testId);
+    userEvent.click(trigger);
+
```
[the remark this answers is not in the document]
Comment (erzhan-temir-mamyrov) [reply packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx:293]: I replaced tag selector with role selector (still using `querySelector` due to `React.createPortal` issue, RTL queries couldn't get portals).

File: packages/react/src/constants/CardPropTypes.js (hunk 1 above)
Comment (erzhan-temir-mamyrov) [reply packages/react/src/constants/CardPropTypes.js:234]: This prop is part of specific `TableCardPropTypes` or you mean to move it inside `TableCard` component?

File: packages/react/src/components/Table/TableBody/TableBodyRow/TableExpandRow.jsx (hunk 2 above)
Comment (erzhan-temir-mamyrov) [reply packages/react/src/components/Table/TableBody/TableBodyRow/TableExpandRow.jsx]: Thanks for pointing on it! I couldn't foresee the issue with css class selectors in others tests. I added `.${prefix}--table-expand__button` class and fixed back our tests selectors.

File: packages/react/src/constants/CardPropTypes.js (hunk 1 above)
Comment (davidicus) [reply packages/react/src/constants/CardPropTypes.js:234]: Yes, inside the TableCard component

Comment (erzhan-temir-mamyrov) [reply packages/react/src/constants/CardPropTypes.js:234]: Got it, I will fix it.

File: packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (davidicus) [reply packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx:293]: Seems odd that the RTL would not pick up on the role since that is what the querySelector is looking for but should be good to go.

**Review by davidicus — APPROVED** [review]
This looks good once the branch has been updated and merge conflicts are resolved

File: packages/react/src/components/OverflowMenu/index.jsx [hunk 4]
```diff
@@ -1,18 +1,604 @@
...
+      ? null
+      : {
+          open,
+          prevOpen: open,
+          tooltipAlignment,
+        };
+  }
+
+  componentWillUnmount() {
+    /* istanbul ignore if */
```
Comment (davidicus) [inline packages/react/src/components/OverflowMenu/index.jsx:263]: Why do we ignore this if statement? Is this supposed to ignore the non existent else?

Comment (erzhan-temir-mamyrov) [reply packages/react/src/components/OverflowMenu/index.jsx:263]: @davidicus Thank you for commenting on this! It look like a bug, I will fix it.
