### PR TITLE
fix(card): accessibility violation in card header tooltip

### LINKED ISSUE #3395: [Card] Accessibility violation for no aria-label in card header tooltip.
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
Card is used in Maximo Graphite and accessibility violation is thrown for the card header tooltip.
image

### To Reproduce

1. Go to storybook https://next.carbon-addons-iot-react.com//?path=/story/1-watson-iot-card-card--with-ellipsed-title-tooltip-external-tooltip
2. Check the accessibility tab

### Expected behavior

No accessibility violation for card header tooltip.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: 2.149.0-next.10

### PR DESCRIPTION
**Pull request by kalyanixraut**
#3395

Closes #3395

**Summary**

- Card with a tooltip in the header throws serious accessibility violation for missing aria-label.
image

**Change List (commits, features, bugs, etc)**

- Setting the `iconDescription` prop of `CardTitle`, sets the aria-label to the card header tooltip div and hence gets rid of accessibility violation.

**Acceptance Test (how to verify the PR)**

- Go to storybook /?path=/story/1-watson-iot-card-card--with-ellipsed-title-tooltip-external-tooltip
- Check the Accessibility tab
- The serious violation 'Ensures every ARIA button, link and menuitem has an accessible name' is no more listed.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- As there is no functionality changes, so the Card storybook and all components referring Card should work as before.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by bjornalm — COMMENTED** [review]
code change looks good, but do you know where the snapshot deletions come from?

**Comment by kalyanixraut** [comment]
> code change looks good, but do you know where the snapshot deletions come from?

Hi @bjornalm , thanks for reviewing. When I ran `yarn run test:base -u` to resolve snapshot failures those deletions happened automatically. Not sure whats the cause of it.

**Review by bjornalm — APPROVED** [review]
I also noticed the snapshots deletion in next. I think they will go away now if you pull in latest next and run a new test:update

**Comment by kalyanixraut** [comment]
> I also noticed the snapshots deletion in next. I think they will go away now if you pull in latest next and run a new test:update

Done, thanks.

File: packages/react/src/components/Card/Card.jsx [hunk 1]
```diff
@@ -516,6 +516,7 @@ const Card = (props) => {
                 triggerClassName={`${iotPrefix}--card--header--tooltip`}
                 id={`card-tooltip-${id}`} // https://github.com/carbon-design-system/carbon/pull/6744
                 triggerText=""
+                iconDescription={`card-header-tooltip-${id}`} // To fix accessibility violation.
```
Comment (davidicus) [inline packages/react/src/components/Card/Card.jsx:519]: While we are doing this we may want to add the ability to provide a translatable string from the user. So we check if there is an `i18n.iconDescription`. If so we use that and if not we can use this as a fallback.

File: packages/react/src/components/Card/Card.jsx [hunk 2]
```diff
@@ -516,7 +516,7 @@ const Card = (props) => {
                 triggerClassName={`${iotPrefix}--card--header--tooltip`}
                 id={`card-tooltip-${id}`} // https://github.com/carbon-design-system/carbon/pull/6744
                 triggerText=""
-                iconDescription={`card-header-tooltip-${id}`} // To fix accessibility violation.
+                iconDescription={strings.iconDescription || `card-header-tooltip-${id}`} // To fix accessibility violation.
```
Comment (bjornalm) [inline packages/react/src/components/Card/Card.jsx:519]: We should add this prop to the packages/react/src/constants/CardPropTypes.js and perhaps call it titleTooltipIconDescription and also give that prop a default value like "Tooltip info icon".

Comment (bjornalm) [reply packages/react/src/components/Card/Card.jsx:519]: And since we now merged https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3402 we need to move these changes to the new CardTitle component and also include this new iconDescription prop

**Review by davidicus — APPROVED** [review]
