### PR TITLE
fix(composed-modal): adjust height based on content and available area

### LINKED ISSUE #3077: [ComposedModal] prevent height of modal to change with content
### What package is this for?

- [x] React
- [ ] Angular

### Summary

The height of the modal currently changes with the content, e.g. the height of the modal is decreased if the user reduces the number of items in a list using search. We can set a fixed height of the modal content but doesn't take into account the actual viewport height and if we set the height of the content in `vh` we are still missing information about the space occupied by the surrounding modal (like height of header and footer that could vary).

Not sure what the best solution to this problem is. It could be nice if the content of the modal would be passed the maximum height allowed, which would be the viewport minus all modal paddings, margins, header and footer.

**Additional context** 
image
image

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3077 

**Summary**

- This is a tricky issue, and I'm not certain I love my solution here, but wanted to gather some feedback. Using the refs on the modal elements, I'm measuring the footer/header to know their height to be able to subtract it from the whole modal and know the maxHeight of the content. This is set as a style object on the ModalBody; however, since the Carbon modal's css doesn't have a fixed height (it sets a min-height, and a max-height--and the max-height varies based on screen size)this approach doesn't completely solve the issue of the modal changing height as content grows. It will prevent it from growing too large, but the modal will still change size until it reaches that max-height set on the overall modal. Additionally, I'm setting a css var of the "extrasHeight" (header and footer), so that those can be read by components that use the ComposedModal to set their own height restrictions.

Old summary: ~I'm measuring the height of the window, the modal, the header and footer, and calculating the maximum height the content can be. If the modal is _not_ `isLarge` I set that height as the maxHeight and allow the modal to grow as needed; however, if it _is_ `isLarge` then, I set that as the `height` of the modal body, so that it maintains the same height all the time.~ 

**Change List (commits, features, bugs, etc)**

- measure the window and modal components to calculate a maximum height for the content
- set that height as the maxHeight on the modalBody style
- set a css var of the height of the header/footer combined.

**Acceptance Test (how to verify the PR)**

- check the SelectUserModal stories or TableColumnCustomizationModal stories
- open and close groups in SelectUserModal and see how modal stays the same height (it's using isLarge)
- check the "with many columns and 'Load more'" column customization story

**Regression Test (how to make sure this PR doesn't break old functionality)**

- confirm no height issues exist at various window sizes
- check the ComposedModal stories for regressions with isLarge knob being used or not.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

File: packages/react/src/components/ComposedModal/ComposedModal.jsx [hunk 1]
```diff
@@ -101,90 +122,96 @@ export const ComposedModalPropTypes = {
...
-    } = this.props;
-    const { label, title, helpText } = header;
-    // First check for dataErrors as they are worse than form errors
+  const modalWrapperRef = useRef(null);
 
-    if (__DEV__ && passiveModal && (footer || onSubmit)) {
-      warning(
-        false,
-        'You have set passiveModal to true, but also passed a footer or onSubmit handler.  Your footer will not be rendered.'
+  useEffect(() => {
```
Comment (bjornalm) [inline packages/react/src/components/ComposedModal/ComposedModal.jsx:177]: I wonder if it is better to use `useLayoutEffect` here to prevent the modal from jumping in height on the first render...

File: packages/react/src/components/ComposedModal/ComposedModal.jsx [hunk 2]
```diff
@@ -101,90 +122,96 @@ export const ComposedModalPropTypes = {
...
+    if (modalWrapperRef.current) {
```
Comment (bjornalm) [inline packages/react/src/components/ComposedModal/ComposedModal.jsx:178]: I don't know if  this is working, but perhaps we could use the new useSizeObserver on the `CarbonComposedModal` and on the `ModalBody`. Then subtract the initial height of the ModalBody from the CarbonComposedModal to find out what the modal extras (height including header, footer and paddings etc) is. Then content max height could be set as CSS `calc(100vh - ${extrasHeight}`

Comment (kevinsperrine) [reply packages/react/src/components/ComposedModal/ComposedModal.jsx:178]: Yeah, that was my initial plan, but none of the Carbon ComposedModal parts forward ref, hence the need for the wrapper and selectors. We can certainly do it that way, but it'll just be blocked for a while waiting on Carbon to merge a PR.

File: packages/react/src/components/ComposedModal/ComposedModal.jsx (hunk 1 above)
Comment (kevinsperrine) [reply packages/react/src/components/ComposedModal/ComposedModal.jsx:177]: Yes, I'll make that change.

File: packages/react/src/components/ComposedModal/ComposedModal.jsx (hunk 2 above)
Comment (bjornalm) [reply packages/react/src/components/ComposedModal/ComposedModal.jsx:178]: Yea I don't know, but I don't think this is time critical. @davidicus What is your take on this, wait a while and get a cleaner solution or merge this now?

File: packages/react/src/components/ComposedModal/ComposedModal.jsx [hunk 3]
```diff
@@ -210,6 +237,8 @@ class ComposedModal extends React.Component {
               // Prevent double scrollbars
               [`${iotPrefix}--composed-modal__body--small-margin-bottom`]: error,
             })}
+            // subtracting 4rem for padding/margin
+            style={{ [isLarge ? 'height' : 'maxHeight']: `calc(${maxContentHeight}px - 3rem)` }}
```
[the remark this answers is not in the document]
Comment (bjornalm) [reply packages/react/src/components/ComposedModal/ComposedModal.jsx:241]: On the other hand, if we only set `maxHeight` it will fix the double scrollbar problem, but we still need a CSS sizes solution and add those to the individual specialised components (SelectUsersModal, TableColumnCustomizationModal etc)

File: packages/react/src/components/ComposedModal/ComposedModal.jsx (hunk 2 above)
Comment (kevinsperrine) [reply packages/react/src/components/ComposedModal/ComposedModal.jsx:178]: I'm fine to wait. I can open the PRs on the carbon side to add the forwardRefs. I think that'll be better. This is pretty hacky.

**Comment by kevinsperrine** [comment]
@davidicus Added the carbon issue in the summary. It was merged last week, but haven't been released yet.

**Review by davidicus — APPROVED** [review]
