### PR TITLE
fix(date-time-picker): date time picker styles and add keyboard navigation/tests

### LINKED ISSUE #2433: [DateTimePicker]: Adjust styles and a11y after design review
There are still a few items in the design review that we need to tackle on the DateTimePicker component in react.

1. Tooltip and styles
2. keyboard navigation
3. inconsistence use of menu controls

PDF: [UI audit - Date Time Range Selector - Angular (v1).pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6668937/UI.audit.-.Date.Time.Range.Selector.-.Angular.v1.pdf)

UI audit - Date Time Range Selector - Angular (v1)  @2x

_Originally posted by @Najil-K in https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2365#issuecomment-863073400_

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2433 

Depends on #2761 since the e2e tests already existed in that coverage PR.

**Summary**

- This begins the process of bring the DateTimePicker into design alignment. There are some elements that haven't been created yet, so this only handles basic items like spacing from a design standpoint. However, it also adds keyboard navigation for accessibility.

**Change List (commits, features, bugs, etc)**

- shows tooltip on hover/focus
- match tooltip styles to designs
- add keyboard navigation to presets list (tab, arrow keys)
- fix keyboard navigation between Relative, Absolute radios (arrow keys)
- adds cypress-plugin-tab plugin for tab testing
- fix cypress viewport sizes that mismatched between local and CI
- add e2e tests for keyboard navigation

**Acceptance Test (how to verify the PR)**

- DateTimePicker stories should better match provided designs
- The DateTimePicker can be navigated and used via the keyboard
- still meets 90%+ testing threshold

**Regression Test (how to make sure this PR doesn't break old functionality)**

- No averse effects in any stories
- All old stories should be unchanged.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by stuckless — APPROVED** [review]

File: packages/react/src/components/DateTimePicker/DateTimePicker.jsx [hunk 1]
```diff
@@ -477,8 +498,96 @@ const DateTimePicker = ({
...
+        setIsExpanded(!isExpanded);
+        break;
+    }
+  };
+
+  /**
+   * Moves up the preset list to the previous focusable element or wraps around to the bottom
+   * if already at the top.
+   */
+  const moveToPreviousElement = () => {
```
Comment (davidicus) [inline packages/react/src/components/DateTimePicker/DateTimePicker.jsx:537]: Could these be helper utilities that we can pull out so they can be used elsewhere? Or are these specific to this component?

Comment (kevinsperrine) [reply packages/react/src/components/DateTimePicker/DateTimePicker.jsx:537]: theoretically, I suppose they could. I don't know exactly where we would use it, but it's only looking for siblings with `tabindex != -1` and wrapping around the ends of the array to move through them...

**Review by davidicus — APPROVED** [review]
nice work!
