### PR TITLE
fix(datetime picker): externally set range not selected in calendar

### LINKED ISSUE #1482: [DateTime Picker] Externally set date range is not selected in calendar
### Describe the bug

Externally set date range is not properly selected in calendar. E.g. If the range value of 2020-04-01 12:34 to 2020-04-06 10:49 is set, the calendar shows July 31 2025 as the active selection.
https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-datetime-picker--selected-absolute

DateTimePicker_Issue

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-datetime-picker--selected-absolute
2. Click on the calendar icon
3. See the issue

### Expected behavior

The active selection in calendar should match the set date range.

### Environment/versions:

- OS: All
- Browser: All

### Additional context
N/A

### Specific timeline issues / requests
N/A

### PR DESCRIPTION
**Pull request by navjeets**
Closes #1482 #1494

**Summary**

- The external value is passed in as "defaultValue". Updated code to ensure that the external value is properly set and assigned to "lastAppliedValue" as well.
- The absolute value was not being passed to Carbon DatePicker correctly. Current code passes the absolute value startDate and endDate to DatePickerInput as "value" prop. DatePickerInput doesn't have any "value" prop. Passing the start and end date as an array to DatePicker's "value" prop.
- DatePicker dateFormat has been set as "m/d/Y". However, the format of the date that is passed to the "value" prop depends on the "dateTimeMask". So when we set the "dateTimeMask" to anything but "MM/DD/YYYY", the current selection is not set in calendar. Changed code to format the absolute value dates to "MM/DD/YYYY" before passing to DatePicker so that its independent of the format specified in "dateTimeMask".

**Change List (commits, features, bugs, etc)**

- https://github.com/carbon-design-system/carbon-addons-iot-react/commit/49187d9a2065cfb7316100ab39d75bd853adeb60

**Acceptance Test (how to verify the PR)**

- Tested the changes in Predict Asset Timeline widget.

### CODE REVIEW

**Comment by navjeets** [comment]
> @navjeets could we add a unit test to cover this functionality?

Sure. I'll add a new unit test for checking internal state after updating the default value.

File: src/components/DateTimePicker/DateTimePicker.jsx [hunk 1]
```diff
@@ -551,7 +550,9 @@ const DateTimePicker = ({
   useEffect(
     () => {
       if (defaultValue || humanValue === null) {
-        parseDefaultValue();
+        parseDefaultValue(defaultValue);
+        setLastAppliedValue(defaultValue);
+        setIsExpanded(false);
```
Comment (tay1orjones) [inline src/components/DateTimePicker/DateTimePicker.jsx:555]: Why should the menu close when the defaultValue changes? What if the `expanded` prop is passed in as true?

File: src/components/DateTimePicker/DateTimePicker.jsx [hunk 2]
```diff
@@ -828,19 +827,17 @@ const DateTimePicker = ({
                         ref={datePickerRef}
                         onChange={onDatePickerChange}
                         onClose={onDatePickerClose}
+                        value={
+                          absoluteValue
+                            ? [
+                                moment(absoluteValue.startDate, dateTimeMask).format('MM/DD/YYYY'),
+                                moment(absoluteValue.endDate, dateTimeMask).format('MM/DD/YYYY'),
```
Comment (tay1orjones) [inline src/components/DateTimePicker/DateTimePicker.jsx:834]: I don't think it's necessary to format on every render. We also do this same format in `onDatePickerChange`, so on non-initial renders I think the format isn't necessary. 

Could we unify this and improve the performance by placing the format inside a useEffect that only runs when the absoluteValue changes? Or maybe a useEffect with an empty dependency array so it's only ran on mount and unmount?

File: src/components/DateTimePicker/DateTimePicker.jsx (hunk 1 above)
Comment (navjeets) [reply src/components/DateTimePicker/DateTimePicker.jsx]: Removed setIsExpanded(false);

**Comment by navjeets** [comment]
> > @navjeets could we add a unit test to cover this functionality?
> 
> Sure. I'll add a new unit test for checking internal state after updating the default value.

Added new test case 'should render with programmatically set absolute range'

File: src/components/DateTimePicker/DateTimePicker.jsx (hunk 2 above)
Comment (navjeets) [reply src/components/DateTimePicker/DateTimePicker.jsx]: Moved the date formatting code to parseDefaultValue() function so that it executes only when the default value is set.

File: src/components/DateTimePicker/DateTimePicker.test.jsx [hunk 3]
```diff
@@ -348,6 +348,61 @@ describe('DateTimePicker', () => {
     ).toHaveLength(1);
   });
 
+  it('should render with programmatically set absolute range', () => {
+    const wrapper = mount(<DateTimePicker {...dateTimePickerProps} />);
```
Comment (davidicus) [inline src/components/DateTimePicker/DateTimePicker.test.jsx:352]: Since this is a sev 1 bug fix I am not going to hold up the PR but in the future we want to utilize the react testing library for any new test.

**Comment by davidicus** [comment]
@navjeets Thank you for the contribution and getting this bug fixed!
